<?php

class KelurahanSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run() {
		
		$temp1 = array(

			# Balikpapan
			array('nama' => 'Baru Ilir', 'id_kecamatan' => '1'),
			array('nama' => 'Baru Tengah', 'id_kecamatan' => '1'),
			array('nama' => 'Baru Ulu', 'id_kecamatan' => '1'),
			array('nama' => 'Kariangau', 'id_kecamatan' => '1'),
			array('nama' => 'Marga Sari', 'id_kecamatan' => '1'),
			array('nama' => 'Marga Mulyo', 'id_kecamatan' => '1'),
			
			array('nama' => 'Damai', 'id_kecamatan' => '2'),
			array('nama' => 'Klandasan Ilir', 'id_kecamatan' => '2'),
			array('nama' => 'Klandasan Ulu', 'id_kecamatan' => '2'),
			array('nama' => 'Prapatan', 'id_kecamatan' => '2'),
			array('nama' => 'Telaga Sari', 'id_kecamatan' => '2'),
			
			array('nama' => 'Damai Bahagia', 'id_kecamatan' => '3'),
			array('nama' => 'Damai Baru', 'id_kecamatan' => '3'),
			array('nama' => 'Gunung Bahagia', 'id_kecamatan' => '3'),
			array('nama' => 'Sepinggan', 'id_kecamatan' => '3'),
			array('nama' => 'Sepinggan Baru', 'id_kecamatan' => '3'),
			array('nama' => 'Sepinggan Raya', 'id_kecamatan' => '3'),
			array('nama' => 'Sungai Nangka', 'id_kecamatan' => '3'),
			
			array('nama' => 'Gunung Sari Ilir', 'id_kecamatan' => '4'),
			array('nama' => 'Gunung Sari Ulu', 'id_kecamatan' => '4'),
			array('nama' => 'Karang Jati', 'id_kecamatan' => '4'),
			array('nama' => 'Karang Rejo', 'id_kecamatan' => '4'),
			array('nama' => 'Mekar Sari', 'id_kecamatan' => '4'),
			array('nama' => 'Sumber Rejo', 'id_kecamatan' => '4'),
			
			array('nama' => 'Manggar', 'id_kecamatan' => '5'),
			array('nama' => 'Manggar Baru', 'id_kecamatan' => '5'),
			array('nama' => 'Teritip', 'id_kecamatan' => '5'),
			
			array('nama' => 'Batu Ampar', 'id_kecamatan' => '6'),
			array('nama' => 'Graha Indah', 'id_kecamatan' => '6'),
			array('nama' => 'Gunung Samarinda', 'id_kecamatan' => '6'),
			array('nama' => 'Gunung Samarinda Baru', 'id_kecamatan' => '6'),
			array('nama' => 'Karang Joang', 'id_kecamatan' => '6'),
			array('nama' => 'Muara Rapak', 'id_kecamatan' => '6'),

			# Berau
			array('nama' => 'Ampen Medang', 'id_kecamatan' => '7'),
			array('nama' => 'Balikukup', 'id_kecamatan' => '7'),
			array('nama' => 'Batu Putih', 'id_kecamatan' => '7'),
			array('nama' => 'Kayu Indah', 'id_kecamatan' => '7'),
			array('nama' => 'Lobang Kelatak', 'id_kecamatan' => '7'),
			array('nama' => 'Sumber Agung', 'id_kecamatan' => '7'),
			array('nama' => 'Tembudan', 'id_kecamatan' => '7'),

			array('nama' => 'Biatan Bapinang', 'id_kecamatan' => '8'),
			array('nama' => 'Biatan Baru', 'id_kecamatan' => '8'),
			array('nama' => 'Biatan Ilir', 'id_kecamatan' => '8'),
			array('nama' => 'Biatan Lempake', 'id_kecamatan' => '8'),
			array('nama' => 'Biatan Ulu', 'id_kecamatan' => '8'),
			array('nama' => 'Bukit Makmur Jaya', 'id_kecamatan' => '8'),
			array('nama' => 'Karangan', 'id_kecamatan' => '8'),
			array('nama' => 'Manunggal Jaya', 'id_kecamatan' => '8'),

			array('nama' => 'Biduk-Biduk', 'id_kecamatan' => '9'),
			array('nama' => 'Giring-Giring', 'id_kecamatan' => '9'),
			array('nama' => 'Pantai Harapan', 'id_kecamatan' => '9'),
			array('nama' => 'Tanjung Prepat', 'id_kecamatan' => '9'),
			array('nama' => 'Teluk Sulaiman', 'id_kecamatan' => '9'),
			array('nama' => 'Teluk Sumbang', 'id_kecamatan' => '9'),

			array('nama' => 'Batu-Batu', 'id_kecamatan' => '10'),
			array('nama' => 'Biarang', 'id_kecamatan' => '10'),
			array('nama' => 'Gunung Tabur', 'id_kecamatan' => '10'),
			array('nama' => 'Maluang', 'id_kecamatan' => '10'),
			array('nama' => 'Melati Jaya', 'id_kecamatan' => '10'),
			array('nama' => 'Merancang Ilir', 'id_kecamatan' => '10'),
			array('nama' => 'Merancang Ulu', 'id_kecamatan' => '10'),
			array('nama' => 'Pulau Besing', 'id_kecamatan' => '10'),
			array('nama' => 'Sambakungan', 'id_kecamatan' => '10'),
			array('nama' => 'Samburakat', 'id_kecamatan' => '10'),
			array('nama' => 'Tasuk', 'id_kecamatan' => '10'),
			
			array('nama' => 'Lesan Dayak', 'id_kecamatan' => '11'),
			array('nama' => 'Long Beliu', 'id_kecamatan' => '11'),
			array('nama' => 'Long Duhung', 'id_kecamatan' => '11'),
			array('nama' => 'Long Keluh', 'id_kecamatan' => '11'),
			array('nama' => 'Long Lamcin', 'id_kecamatan' => '11'),
			array('nama' => 'Long Pelay', 'id_kecamatan' => '11'),
			array('nama' => 'Long Sului', 'id_kecamatan' => '11'),
			array('nama' => 'Mapulu', 'id_kecamatan' => '11'),
			array('nama' => 'Merabu', 'id_kecamatan' => '11'),
			array('nama' => 'Merapun', 'id_kecamatan' => '11'),
			array('nama' => 'Merasa', 'id_kecamatan' => '11'),
			array('nama' => 'Muara Lesan', 'id_kecamatan' => '11'),
			array('nama' => 'Panaan', 'id_kecamatan' => '11'),
			array('nama' => 'Sido Bangen', 'id_kecamatan' => '11'),
			
			array('nama' => 'Bohesillan', 'id_kecamatan' => '12'),
			array('nama' => 'Payung Payung', 'id_kecamatan' => '12'),
			array('nama' => 'Teluk Alulu', 'id_kecamatan' => '12'),
			array('nama' => 'Teluk Harapan', 'id_kecamatan' => '12'),
			
			array('nama' => 'Kasai', 'id_kecamatan' => '13'),
			array('nama' => 'Pegat Betumbuk', 'id_kecamatan' => '13'),
			array('nama' => 'Pulau Derawan', 'id_kecamatan' => '13'),
			array('nama' => 'Tanjung Batu', 'id_kecamatan' => '13'),
			array('nama' => 'Teluk Semanting', 'id_kecamatan' => '13'),

			array('nama' => 'Bena Baru', 'id_kecamatan' => '14'),
			array('nama' => 'Gurimbang', 'id_kecamatan' => '14'),
			array('nama' => 'Inaran', 'id_kecamatan' => '14'),
			array('nama' => 'Long Lanuk', 'id_kecamatan' => '14'),
			array('nama' => 'Pegat Bukur', 'id_kecamatan' => '14'),
			array('nama' => 'Mengkajang', 'id_kecamatan' => '14'),
			array('nama' => 'Pilanjau', 'id_kecamatan' => '14'),
			array('nama' => 'Rantau Panjang', 'id_kecamatan' => '14'),
			array('nama' => 'Sambaliung', 'id_kecamatan' => '14'),
			array('nama' => 'Sei Bebanir Bangun', 'id_kecamatan' => '14'),
			array('nama' => 'Suaran', 'id_kecamatan' => '14'),
			array('nama' => 'Sukan Tengah', 'id_kecamatan' => '14'),
			array('nama' => 'Tanjung Perangat', 'id_kecamatan' => '14'),
			array('nama' => 'Tumbit Dayak', 'id_kecamatan' => '14'),
			
			array('nama' => 'Bukit Makmur', 'id_kecamatan' => '15'),
			array('nama' => 'Gunung Sari', 'id_kecamatan' => '15'),
			array('nama' => 'Harapan Jaya', 'id_kecamatan' => '15'),
			array('nama' => 'Long Ayan', 'id_kecamatan' => '15'),
			array('nama' => 'Long Ayap', 'id_kecamatan' => '15'),
			array('nama' => 'Long La Ai', 'id_kecamatan' => '15'),
			array('nama' => 'Pandan Sari', 'id_kecamatan' => '15'),
			array('nama' => 'Punan Segah', 'id_kecamatan' => '15'),
			array('nama' => 'Punan Mahakam', 'id_kecamatan' => '15'),
			array('nama' => 'Punan Malinau', 'id_kecamatan' => '15'),
			array('nama' => 'Tepian Buah', 'id_kecamatan' => '15'),
			
			array('nama' => 'Tubaan', 'id_kecamatan' => '16'),
			array('nama' => 'Buyung Buyung', 'id_kecamatan' => '16'),
			array('nama' => 'Harapan Maju', 'id_kecamatan' => '16'),
			array('nama' => 'Semurut', 'id_kecamatan' => '16'),
			array('nama' => 'Tabalar Muara', 'id_kecamatan' => '16'),
			array('nama' => 'Tabalar Ulu', 'id_kecamatan' => '16'),
			
			array('nama' => 'Bumu Jaya', 'id_kecamatan' => '17'),
			array('nama' => 'Campur Sari', 'id_kecamatan' => '17'),
			array('nama' => 'Dumaring', 'id_kecamatan' => '17'),
			array('nama' => 'Eka Sapta', 'id_kecamatan' => '17'),
			array('nama' => 'Purnasari Jaya', 'id_kecamatan' => '17'),
			array('nama' => 'Suka Murya', 'id_kecamatan' => '17'),
			array('nama' => 'Sumber Mulya', 'id_kecamatan' => '17'),
			array('nama' => 'Talisayan', 'id_kecamatan' => '17'),
			array('nama' => 'Tunggal Bumi', 'id_kecamatan' => '17'),
			
			array('nama' => 'Bugis', 'id_kecamatan' => '18'),
			array('nama' => 'Gayam', 'id_kecamatan' => '18'),
			array('nama' => 'Gunung Panjang', 'id_kecamatan' => '18'),
			array('nama' => 'Karang Ambun', 'id_kecamatan' => '18'),
			array('nama' => 'Sungai Bedungun', 'id_kecamatan' => '18'),
			array('nama' => 'Tanjung Redeb', 'id_kecamatan' => '18'),
			
			array('nama' => 'Labanan Jaya', 'id_kecamatan' => '19'),
			array('nama' => 'Labanan Makarti', 'id_kecamatan' => '19'),
			array('nama' => 'Labanan Makmur', 'id_kecamatan' => '19'),
			array('nama' => 'Rinding', 'id_kecamatan' => '19'),
			array('nama' => 'Teluk Bayur', 'id_kecamatan' => '19'),
			array('nama' => 'Tumbit Melayu', 'id_kecamatan' => '19'),

			# Bontang
			array('nama' => 'Belimbing', 'id_kecamatan' => '20'),
			array('nama' => 'Gunung Telihan', 'id_kecamatan' => '20'),
			array('nama' => 'Kanaan', 'id_kecamatan' => '20'),
			
			array('nama' => 'Berebas Pantai', 'id_kecamatan' => '21'),
			array('nama' => 'Berebas Tengah', 'id_kecamatan' => '21'),
			array('nama' => 'Bontang Lestari', 'id_kecamatan' => '21'),
			array('nama' => 'Sitampo', 'id_kecamatan' => '21'),
			array('nama' => 'Tanjung Laut', 'id_kecamatan' => '21'),
			array('nama' => 'Tanjung Laut Indah', 'id_kecamatan' => '21'),
			
			array('nama' => 'Api-Api', 'id_kecamatan' => '22'),
			array('nama' => 'Bontang Baru', 'id_kecamatan' => '22'),
			array('nama' => 'Bontang Kuala', 'id_kecamatan' => '22'),
			array('nama' => 'Guntung', 'id_kecamatan' => '22'),
			array('nama' => 'Guntung Elai', 'id_kecamatan' => '22'),
			array('nama' => 'Loktuan', 'id_kecamatan' => '22'),
			
			# Bulungan
			array('nama' => 'Bunyu Barat', 'id_kecamatan' => '23'),
			array('nama' => 'Bunyu Selatan', 'id_kecamatan' => '23'),
			array('nama' => 'Bunyu Timur', 'id_kecamatan' => '23'),

			array('nama' => 'Lepak Aru', 'id_kecamatan' => '24'),
			array('nama' => 'Long Bia', 'id_kecamatan' => '24'),
			array('nama' => 'Long Buang', 'id_kecamatan' => '24'),
			array('nama' => 'Long Lasan', 'id_kecamatan' => '24'),
			array('nama' => 'Long Lejuh', 'id_kecamatan' => '24'),
			array('nama' => 'Long Lian', 'id_kecamatan' => '24'),
			array('nama' => 'Long Pelaah', 'id_kecamatan' => '24'),
			array('nama' => 'Long Pelban', 'id_kecamatan' => '24'),
			array('nama' => 'Long Peso', 'id_kecamatan' => '24'),
			array('nama' => 'Muara Pengean', 'id_kecamatan' => '24'),
			
			array('nama' => 'Long Bang', 'id_kecamatan' => '25'),
			array('nama' => 'Long Bang Hulu', 'id_kecamatan' => '25'),
			array('nama' => 'Long Lembu', 'id_kecamatan' => '25'),
			array('nama' => 'Long Telenjau', 'id_kecamatan' => '25'),
			array('nama' => 'Long Tengu', 'id_kecamatan' => '25'),
			array('nama' => 'Naha Anya', 'id_kecamatan' => '25'),
			
			array('nama' => 'Ambalat', 'id_kecamatan' => '26'),
			array('nama' => 'Anjar Arip', 'id_kecamatan' => '26'),
			array('nama' => 'Bambang', 'id_kecamatan' => '26'),
			array('nama' => 'Bekiliu', 'id_kecamatan' => '26'),
			array('nama' => 'Bunau', 'id_kecamatan' => '26'),
			array('nama' => 'Kelembunan', 'id_kecamatan' => '26'),
			array('nama' => 'Kelincauan', 'id_kecamatan' => '26'),
			array('nama' => 'Kelising', 'id_kecamatan' => '26'),
			array('nama' => 'Kendari', 'id_kecamatan' => '26'),
			array('nama' => 'Keriting', 'id_kecamatan' => '26'),
			array('nama' => 'Liagu', 'id_kecamatan' => '26'),
			array('nama' => 'Maritam', 'id_kecamatan' => '26'),
			array('nama' => 'Paru Abang', 'id_kecamatan' => '26'),
			array('nama' => 'Pentian', 'id_kecamatan' => '26'),
			array('nama' => 'Punan Dulau', 'id_kecamatan' => '26'),
			array('nama' => 'Pungit', 'id_kecamatan' => '26'),
			array('nama' => 'Sekatak Bengara', 'id_kecamatan' => '26'),
			array('nama' => 'Sekatak Buji', 'id_kecamatan' => '26'),
			array('nama' => 'Tenggiling', 'id_kecamatan' => '26'),
			array('nama' => 'Terindak', 'id_kecamatan' => '26'),
			array('nama' => 'Turung', 'id_kecamatan' => '26'),
			array('nama' => 'Ujang', 'id_kecamatan' => '26'),
			
			array('nama' => 'Antutan', 'id_kecamatan' => '27'),
			array('nama' => 'Gunung Putih', 'id_kecamatan' => '27'),
			array('nama' => 'Karang Anyar', 'id_kecamatan' => '27'),
			array('nama' => 'Pejalin', 'id_kecamatan' => '27'),
			array('nama' => 'Tanjung Palas Hilir', 'id_kecamatan' => '27'),
			array('nama' => 'Tanjung Palas Hulu', 'id_kecamatan' => '27'),
			array('nama' => 'Tanjung Palas Tengah', 'id_kecamatan' => '27'),
			array('nama' => 'Teras Baru', 'id_kecamatan' => '27'),
			array('nama' => 'Teras Nawang', 'id_kecamatan' => '27'),
			
			array('nama' => 'Long Beluah', 'id_kecamatan' => '28'),
			array('nama' => 'Long Pari', 'id_kecamatan' => '28'),
			array('nama' => 'Long Sam', 'id_kecamatan' => '28'),
			array('nama' => 'Mara Hilir', 'id_kecamatan' => '28'),
			array('nama' => 'Mara Satu', 'id_kecamatan' => '28'),
			
			array('nama' => 'Salim Batu', 'id_kecamatan' => '29'),
			array('nama' => 'Silva Rahayu', 'id_kecamatan' => '29'),
			array('nama' => 'Tanjung Buka', 'id_kecamatan' => '29'),
			
			array('nama' => 'Binai', 'id_kecamatan' => '30'),
			array('nama' => 'Mangku Padi', 'id_kecamatan' => '30'),
			array('nama' => 'Pura Sajau', 'id_kecamatan' => '30'),
			array('nama' => 'Sajau', 'id_kecamatan' => '30'),
			array('nama' => 'Sajau Hilir', 'id_kecamatan' => '30'),
			array('nama' => 'Tanah Kuning', 'id_kecamatan' => '30'),
			array('nama' => 'Tanjung Agung', 'id_kecamatan' => '30'),
			array('nama' => 'Wono Mulyo', 'id_kecamatan' => '30'),
			
			array('nama' => 'Ardi Mulyo', 'id_kecamatan' => '31'),
			array('nama' => 'Karang Agung', 'id_kecamatan' => '31'),
			array('nama' => 'Kelumbir', 'id_kecamatan' => '31'),
			array('nama' => 'Panca Agung', 'id_kecamatan' => '31'),
			array('nama' => 'Pimping', 'id_kecamatan' => '31'),
			array('nama' => 'Ruhui Rahayu', 'id_kecamatan' => '31'),
			
			array('nama' => 'Apung', 'id_kecamatan' => '32'),
			array('nama' => 'Bumi Rahayu', 'id_kecamatan' => '32'),
			array('nama' => 'Gunung Sari', 'id_kecamatan' => '32'),
			array('nama' => 'Gunung Seriang', 'id_kecamatan' => '32'),
			array('nama' => 'Jelarai Selor', 'id_kecamatan' => '32'),
			array('nama' => 'Tanjung Selor Hilir', 'id_kecamatan' => '32'),
			array('nama' => 'Tanjung Selor Timur', 'id_kecamatan' => '32'),
			array('nama' => 'Tanjung Selor Ulu', 'id_kecamatan' => '32'),
			array('nama' => 'Tengkapak', 'id_kecamatan' => '32'),
			
			# Kutai Barat
			array('nama' => 'Asa', 'id_kecamatan' => '33'),
			array('nama' => 'Balok Asa', 'id_kecamatan' => '33'),
			array('nama' => 'Barong Tongkok', 'id_kecamatan' => '33'),
			array('nama' => 'Belempung Ulaq', 'id_kecamatan' => '33'),
			array('nama' => 'Engkuni Pasek', 'id_kecamatan' => '33'),
			array('nama' => 'Geleo Asa', 'id_kecamatan' => '33'),
			array('nama' => 'Geleo Baru', 'id_kecamatan' => '33'),
			array('nama' => 'Gemuhan Asa', 'id_kecamatan' => '33'),
			array('nama' => 'Juaq Asa', 'id_kecamatan' => '33'),
			array('nama' => 'Juhan Asa', 'id_kecamatan' => '33'),
			array('nama' => 'Mencimai', 'id_kecamatan' => '33'),
			array('nama' => 'Muara Asa', 'id_kecamatan' => '33'),
			array('nama' => 'Ngenyan Asa', 'id_kecamatan' => '33'),
			array('nama' => 'Ombau Asa', 'id_kecamatan' => '33'),
			array('nama' => 'Ongko Asa', 'id_kecamatan' => '33'),
			array('nama' => 'Pepes Eheng', 'id_kecamatan' => '33'),
			array('nama' => 'Pepes Asa', 'id_kecamatan' => '33'),
			array('nama' => 'Rejo Basuki', 'id_kecamatan' => '33'),
			array('nama' => 'Sendawar', 'id_kecamatan' => '33'),
			array('nama' => 'Simpang Ray', 'id_kecamatan' => '33'),
			array('nama' => 'Sumber Sari', 'id_kecamatan' => '33'),
		
			array('nama' => 'Anan Jaya', 'id_kecamatan' => '34'),
			array('nama' => 'Dilang Puti', 'id_kecamatan' => '34'),
			array('nama' => 'Jelmu Sibak', 'id_kecamatan' => '34'),
			array('nama' => 'Penarung', 'id_kecamatan' => '34'),
			array('nama' => 'Randa Emas', 'id_kecamatan' => '34'),
			array('nama' => 'Sambang', 'id_kecamatan' => '34'),
			array('nama' => 'Suakong', 'id_kecamatan' => '34'),
			array('nama' => 'Tende', 'id_kecamatan' => '34'),
			array('nama' => 'Tukuq', 'id_kecamatan' => '34'),
			
			array('nama' => 'Bukit Harapan', 'id_kecamatan' => '35'),
			array('nama' => 'Deraya', 'id_kecamatan' => '35'),
			array('nama' => 'Gerungung', 'id_kecamatan' => '35'),
			array('nama' => 'Jambuk', 'id_kecamatan' => '35'),
			array('nama' => 'Jambuk Makmur', 'id_kecamatan' => '35'),
			array('nama' => 'Lemper', 'id_kecamatan' => '35'),
			array('nama' => 'Muara Gusik', 'id_kecamatan' => '35'),
			array('nama' => 'Muara Kedang', 'id_kecamatan' => '35'),
			array('nama' => 'Muara Siram', 'id_kecamatan' => '35'),
			array('nama' => 'Penawai', 'id_kecamatan' => '35'),
			array('nama' => 'Pereng Taliq', 'id_kecamatan' => '35'),
			array('nama' => 'Resak', 'id_kecamatan' => '35'),
			array('nama' => 'Siram Jaya', 'id_kecamatan' => '35'),
			array('nama' => 'Siram Makmur', 'id_kecamatan' => '35'),
			array('nama' => 'Tanjung Sari', 'id_kecamatan' => '35'),
			array('nama' => 'Tanjung Soke', 'id_kecamatan' => '35'),
			
			array('nama' => 'Benung', 'id_kecamatan' => '36'),
			array('nama' => 'Bermai', 'id_kecamatan' => '36'),
			array('nama' => 'Besiq', 'id_kecamatan' => '36'),
			array('nama' => 'Damai Kota', 'id_kecamatan' => '36'),
			array('nama' => 'Damai Seberang', 'id_kecamatan' => '36'),
			array('nama' => 'Jengan Danum', 'id_kecamatan' => '36'),
			array('nama' => 'Keay', 'id_kecamatan' => '36'),
			array('nama' => 'Lumpat Dahuq', 'id_kecamatan' => '36'),
			array('nama' => 'Mantar', 'id_kecamatan' => '36'),
			array('nama' => 'Mendika', 'id_kecamatan' => '36'),
			array('nama' => 'Muara Bomboy', 'id_kecamatan' => '36'),
			array('nama' => 'Muara Niliq', 'id_kecamatan' => '36'),
			array('nama' => 'Muara Nyahing', 'id_kecamatan' => '36'),
			array('nama' => 'Muara Tokong', 'id_kecamatan' => '36'),
			array('nama' => 'Sempatin', 'id_kecamatan' => '36'),
			array('nama' => 'Tapulang', 'id_kecamatan' => '36'),

			array('nama' => 'Bekokong Makmur', 'id_kecamatan' => '37'),
			array('nama' => 'Lembonah', 'id_kecamatan' => '37'),
			array('nama' => 'Mancong', 'id_kecamatan' => '37'),
			array('nama' => 'Muara Nayan', 'id_kecamatan' => '37'),
			array('nama' => 'Muara Ohong', 'id_kecamatan' => '37'),
			array('nama' => 'Muara Tae', 'id_kecamatan' => '37'),
			array('nama' => 'Pentat', 'id_kecamatan' => '37'),
			array('nama' => 'Perigiq', 'id_kecamatan' => '37'),
			array('nama' => 'Pulau Lanting', 'id_kecamatan' => '37'),
			array('nama' => 'Tanjung Isuy', 'id_kecamatan' => '37'),
			array('nama' => 'Tanjung Jan', 'id_kecamatan' => '37'),
			array('nama' => 'Tanjung Jone', 'id_kecamatan' => '37'),
			
			array('nama' => 'Danum Paroy', 'id_kecamatan' => '38'),
			array('nama' => 'Laham', 'id_kecamatan' => '38'),
			array('nama' => 'Long Gelawang', 'id_kecamatan' => '38'),
			array('nama' => 'Muara Ratah', 'id_kecamatan' => '38'),
			array('nama' => 'Nyaribungan', 'id_kecamatan' => '38'),
			
			array('nama' => 'Bangun Sari', 'id_kecamatan' => '39'),
			array('nama' => 'Bigung Baru', 'id_kecamatan' => '39'),
			array('nama' => 'Linggar Amer', 'id_kecamatan' => '39'),
			array('nama' => 'Linggar Bigung', 'id_kecamatan' => '39'),
			array('nama' => 'Linggar Kebut', 'id_kecamatan' => '39'),
			array('nama' => 'Linggar Mapan', 'id_kecamatan' => '39'),
			array('nama' => 'Linggar Melapeh', 'id_kecamatan' => '39'),
			array('nama' => 'Linggar Mencelew', 'id_kecamatan' => '39'),
			array('nama' => 'Melapeh Baru', 'id_kecamatan' => '39'),
			array('nama' => 'Purwodadi', 'id_kecamatan' => '39'),
			array('nama' => 'Tutung', 'id_kecamatan' => '39'),
			
			array('nama' => 'Long Apari', 'id_kecamatan' => '40'),
			array('nama' => 'Long Kerioq', 'id_kecamatan' => '40'),
			array('nama' => 'Long Penaneh I', 'id_kecamatan' => '40'),
			array('nama' => 'Long Penaneh II', 'id_kecamatan' => '40'),
			array('nama' => 'Long Penaneh III', 'id_kecamatan' => '40'),
			array('nama' => 'Naha Buan', 'id_kecamatan' => '40'),
			array('nama' => 'Naha Silat', 'id_kecamatan' => '40'),
			array('nama' => 'Naha Tifab', 'id_kecamatan' => '40'),
			array('nama' => "Tiong Bu'u", 'id_kecamatan' => '40'),
			array('nama' => 'Tiong Ohang', 'id_kecamatan' => '40'),

			array('nama' => 'Batu Majang', 'id_kecamatan' => '41'),
			array('nama' => 'Batuq Kelo', 'id_kecamatan' => '41'),
			array('nama' => 'Long Bagun Ilir', 'id_kecamatan' => '41'),
			array('nama' => 'Long Bagun Ulu', 'id_kecamatan' => '41'),
			array('nama' => 'Long Harai', 'id_kecamatan' => '41'),
			array('nama' => 'Long Melaham', 'id_kecamatan' => '41'),
			array('nama' => 'Long Merah', 'id_kecamatan' => '41'),
			array('nama' => 'Memahak Besar', 'id_kecamatan' => '41'),
			array('nama' => 'Memahak Ulu', 'id_kecamatan' => '41'),
			array('nama' => 'Rukun Damau', 'id_kecamatan' => '41'),
			array('nama' => 'Ujoh Bilang', 'id_kecamatan' => '41'),
	
			array('nama' => 'Datah Bilang Baru', 'id_kecamatan' => '42'),
			array('nama' => 'Datah Bilang Ilir', 'id_kecamatan' => '42'),
			array('nama' => 'Datah Bilang Ulu', 'id_kecamatan' => '42'),
			array('nama' => 'Long Hubung', 'id_kecamatan' => '42'),
			array('nama' => 'Lutan', 'id_kecamatan' => '42'),
			array('nama' => 'Matalibaq', 'id_kecamatan' => '42'),
			array('nama' => 'Memahak Teboq', 'id_kecamatan' => '42'),
			array('nama' => 'Sirau', 'id_kecamatan' => '42'),
			array('nama' => 'Tripariq Makmur', 'id_kecamatan' => '42'),
			array('nama' => 'Wana Pariq', 'id_kecamatan' => '42'),
	
			array('nama' => 'Anah', 'id_kecamatan' => '43'),
			array('nama' => 'Kelian Luar', 'id_kecamatan' => '43'),
			array('nama' => 'Keliwai', 'id_kecamatan' => '43'),
			array('nama' => 'Long Daliq', 'id_kecamatan' => '43'),
			array('nama' => 'Long Iram Bayan', 'id_kecamatan' => '43'),
			array('nama' => 'Long Iram Ilir', 'id_kecamatan' => '43'),
			array('nama' => 'Long Iram Kota', 'id_kecamatan' => '43'),
			array('nama' => 'Long Iram Seberang', 'id_kecamatan' => '43'),
			array('nama' => 'Muara Leban', 'id_kecamatan' => '43'),
			array('nama' => 'Sukomulyo', 'id_kecamatan' => '43'),
			array('nama' => 'Ujoh Halang', 'id_kecamatan' => '43'),
			
			array('nama' => 'Detah Naha', 'id_kecamatan' => '44'),
			array('nama' => 'Delang Kerohong', 'id_kecamatan' => '44'),
			array('nama' => 'Lirung Ubing', 'id_kecamatan' => '44'),
			array('nama' => 'Liu Mulang', 'id_kecamatan' => '44'),
			array('nama' => 'Long Isun', 'id_kecamatan' => '44'),
			array('nama' => 'Long Lunuk', 'id_kecamatan' => '44'),
			array('nama' => 'Long Lunuk Baru', 'id_kecamatan' => '44'),
			array('nama' => 'Long Pahangai I', 'id_kecamatan' => '44'),
			array('nama' => 'Long Pahangai II', 'id_kecamatan' => '44'),
			array('nama' => 'Long Pakaq', 'id_kecamatan' => '44'),
			array('nama' => 'Long Pakaq Baru', 'id_kecamatan' => '44'),
			array('nama' => 'Long Tuyoq', 'id_kecamatan' => '44'),
			array('nama' => 'Naha Aru', 'id_kecamatan' => '44'),
			
			array('nama' => 'Empakuq', 'id_kecamatan' => '45'),
			array('nama' => 'Empas', 'id_kecamatan' => '45'),
			array('nama' => 'Melak Ilir', 'id_kecamatan' => '45'),
			array('nama' => 'Melak Ulu', 'id_kecamatan' => '45'),
			array('nama' => 'Muara Benangaq', 'id_kecamatan' => '45'),
			array('nama' => 'Muara Bunyut', 'id_kecamatan' => '45'),
			
			array('nama' => 'Abit', 'id_kecamatan' => '46'),
			array('nama' => 'Gadur', 'id_kecamatan' => '46'),
			array('nama' => 'Gemuruh', 'id_kecamatan' => '46'),
			array('nama' => 'Gunung Rempah', 'id_kecamatan' => '46'),
			array('nama' => 'Jengan', 'id_kecamatan' => '46'),
			array('nama' => 'Karangan', 'id_kecamatan' => '46'),
			array('nama' => 'Kelumpang', 'id_kecamatan' => '46'),
			array('nama' => 'Linggang Marimun', 'id_kecamatan' => '46'),
			array('nama' => 'Merayaq', 'id_kecamatan' => '46'),
			array('nama' => 'Muara Batuq', 'id_kecamatan' => '46'),
			array('nama' => 'Muara Jawaq', 'id_kecamatan' => '46'),
			array('nama' => 'Muara Kalaq', 'id_kecamatan' => '46'),
			array('nama' => 'Rembayan', 'id_kecamatan' => '46'),
			array('nama' => 'Sadaq Lotoq', 'id_kecamatan' => '46'),
			array('nama' => 'Sadaq Tada', 'id_kecamatan' => '46'),
			
			array('nama' => 'Benggeris', 'id_kecamatan' => '47'),
			array('nama' => 'Cempedes', 'id_kecamatan' => '47'),
			array('nama' => 'Dingin', 'id_kecamatan' => '47'),
			array('nama' => 'Lambing', 'id_kecamatan' => '47'),
			array('nama' => 'Lotaq', 'id_kecamatan' => '47'),
			array('nama' => 'Muara Begai', 'id_kecamatan' => '47'),
			array('nama' => 'Muara Lawa', 'id_kecamatan' => '47'),
			array('nama' => 'Pawang', 'id_kecamatan' => '47'),
			
			array('nama' => 'Gunung Bayan', 'id_kecamatan' => '48'),
			array('nama' => 'Jerang Dayak', 'id_kecamatan' => '48'),
			array('nama' => 'Jerang Melayu', 'id_kecamatan' => '48'),
			array('nama' => 'Mendung', 'id_kecamatan' => '48'),
			array('nama' => 'Muara Baroh', 'id_kecamatan' => '48'),
			array('nama' => 'Muara Beloan', 'id_kecamatan' => '48'),
			array('nama' => 'Sebelang', 'id_kecamatan' => '48'),
			array('nama' => 'Tanjung Laong', 'id_kecamatan' => '48'),
			array('nama' => 'Tanjung Pagar', 'id_kecamatan' => '48'),
			array('nama' => 'Teluk Tempudau', 'id_kecamatan' => '48'),
			array('nama' => 'Tepian Ulaq', 'id_kecamatan' => '48'),

			array('nama' => 'Awai', 'id_kecamatan' => '49'),
			array('nama' => 'Dempar', 'id_kecamatan' => '49'),
			array('nama' => 'Intu Lingau', 'id_kecamatan' => '49'),
			array('nama' => 'Jontai', 'id_kecamatan' => '49'),
			array('nama' => 'Lakan Bilem', 'id_kecamatan' => '49'),
			array('nama' => "Mu'ut", 'id_kecamatan' => '49'),
			array('nama' => 'Sembuan', 'id_kecamatan' => '49'),
			array('nama' => 'Senralar', 'id_kecamatan' => '49'),
			array('nama' => 'Temula', 'id_kecamatan' => '49'),
			array('nama' => 'Terajuk', 'id_kecamatan' => '49'),
			
			array('nama' => 'Bakung', 'id_kecamatan' => '50'),
			array('nama' => 'Loa Deras', 'id_kecamatan' => '50'),
			array('nama' => 'Minta', 'id_kecamatan' => '50'),
			array('nama' => 'Penyinggahan Ilir', 'id_kecamatan' => '50'),
			array('nama' => 'Penyinggahan Ulu', 'id_kecamatan' => '50'),
			array('nama' => 'Tanjung Haur', 'id_kecamatan' => '50'),
			
			array('nama' => 'Sekolaq Darat', 'id_kecamatan' => '51'),
			array('nama' => 'Sekolaq Joleq', 'id_kecamatan' => '51'),
			array('nama' => 'Sekolaq Muliaq', 'id_kecamatan' => '51'),
			array('nama' => 'Sekolaq Oday', 'id_kecamatan' => '51'),
			array('nama' => 'Srimulyo', 'id_kecamatan' => '51'),
			array('nama' => 'Sumber Bangun', 'id_kecamatan' => '51'),
			array('nama' => 'Sumber Rejo', 'id_kecamatan' => '51'),
			
			array('nama' => 'Bentas', 'id_kecamatan' => '52'),
			array('nama' => 'Betung', 'id_kecamatan' => '52'),
			array('nama' => 'Kaliq', 'id_kecamatan' => '52'),
			array('nama' => 'Kendisiq', 'id_kecamatan' => '52'),
			array('nama' => 'Kenyanyan', 'id_kecamatan' => '52'),
			array('nama' => 'Kiaq', 'id_kecamatan' => '52'),
			array('nama' => 'Lendian Liang Nayuq', 'id_kecamatan' => '52'),
			array('nama' => 'Muara Kelawit', 'id_kecamatan' => '52'),
			array('nama' => 'Muara Ponaq', 'id_kecamatan' => '52'),
			array('nama' => 'Muhur', 'id_kecamatan' => '52'),
			array('nama' => 'Penawang', 'id_kecamatan' => '52'),
			array('nama' => 'Rikong', 'id_kecamatan' => '52'),
			array('nama' => 'Sang-Sang', 'id_kecamatan' => '52'),
			array('nama' => 'Tanah Mea', 'id_kecamatan' => '52'),
			array('nama' => 'Tebisaq', 'id_kecamatan' => '52'),
			array('nama' => 'Tendiq', 'id_kecamatan' => '52'),

			array('nama' => 'Gabung Baru', 'id_kecamatan' => '53'),
			array('nama' => 'Jelemuq', 'id_kecamatan' => '53'),
			array('nama' => 'Kelian Dalam', 'id_kecamatan' => '53'),
			array('nama' => 'Kelubaq', 'id_kecamatan' => '53'),
			array('nama' => 'Muara Mujan', 'id_kecamatan' => '53'),
			array('nama' => 'Muyub Aket', 'id_kecamatan' => '53'),
			array('nama' => 'Muyub Ilir', 'id_kecamatan' => '53'),
			array('nama' => 'Muyub Ulu', 'id_kecamatan' => '53'),
			array('nama' => 'Purworejo', 'id_kecamatan' => '53'),
			array('nama' => 'Tering Baru', 'id_kecamatan' => '53'),
			array('nama' => 'Tering Lama', 'id_kecamatan' => '53'),
			array('nama' => 'Tering Seberang', 'id_kecamatan' => '53'),
			array('nama' => 'Tukul', 'id_kecamatan' => '53'),
			
			# Kutai Kartanegara
			array('nama' => 'Anggana', 'id_kecamatan' => '54'),
			array('nama' => 'Handil Terusan', 'id_kecamatan' => '54'),
			array('nama' => 'Kutai Lama', 'id_kecamatan' => '54'),
			array('nama' => 'Muara Pantuan', 'id_kecamatan' => '54'),
			array('nama' => 'Sepatin', 'id_kecamatan' => '54'),
			array('nama' => 'Sidomulyo', 'id_kecamatan' => '54'),
			array('nama' => 'Sungai Meriam', 'id_kecamatan' => '54'),
			array('nama' => 'Tani Baru', 'id_kecamatan' => '54'),
			
			array('nama' => 'Bukit Layang', 'id_kecamatan' => '55'),
			array('nama' => 'Genting Tanah', 'id_kecamatan' => '55'),
			array('nama' => 'Hambau', 'id_kecamatan' => '55'),
			array('nama' => 'Kelekat', 'id_kecamatan' => '55'),
			array('nama' => 'Kembang Janggut', 'id_kecamatan' => '55'),
			array('nama' => 'Loa Sakoh', 'id_kecamatan' => '55'),
			array('nama' => 'Long Beleh Haloq', 'id_kecamatan' => '55'),
			array('nama' => 'Long Beleh Modang', 'id_kecamatan' => '55'),
			array('nama' => 'Muai', 'id_kecamatan' => '55'),
			array('nama' => 'Perdana', 'id_kecamatan' => '55'),
			array('nama' => 'Pulau Pinang', 'id_kecamatan' => '55'),
		);

	$temp2 = array(
			array('nama' => 'Kahala', 'id_kecamatan' => '56'),
			array('nama' => 'Kahala Ilir', 'id_kecamatan' => '56'),
			array('nama' => 'Lamin Pulut', 'id_kecamatan' => '56'),
			array('nama' => 'Lamin Telihan', 'id_kecamatan' => '56'),
			array('nama' => 'Semayang', 'id_kecamatan' => '56'),
			array('nama' => 'Teluk Bingkai', 'id_kecamatan' => '56'),
			array('nama' => 'Teluk Muda', 'id_kecamatan' => '56'),
			array('nama' => 'Tuana Tuha', 'id_kecamatan' => '56'),
			array('nama' => 'Tubuhan', 'id_kecamatan' => '56'),
			
			array('nama' => 'Benua Biru', 'id_kecamatan' => '57'),
			array('nama' => 'Kedang Ipil', 'id_kecamatan' => '57'),
			array('nama' => 'Kedang Murung', 'id_kecamatan' => '57'),
			array('nama' => 'Kota Bangun I', 'id_kecamatan' => '57'),
			array('nama' => 'Kota Bangun II', 'id_kecamatan' => '57'),
			array('nama' => 'Kota Bangun III', 'id_kecamatan' => '57'),
			array('nama' => 'Kota Bangun Ilir', 'id_kecamatan' => '57'),
			array('nama' => 'Kota Bangun Seberang', 'id_kecamatan' => '57'),
			array('nama' => 'Kota Bangun Ulu', 'id_kecamatan' => '57'),
			array('nama' => 'Liang', 'id_kecamatan' => '57'),
			array('nama' => 'Liang Ulu', 'id_kecamatan' => '57'),
			array('nama' => 'Loleng', 'id_kecamatan' => '57'),
			array('nama' => 'Muhuran', 'id_kecamatan' => '57'),
			array('nama' => 'Pela', 'id_kecamatan' => '57'),
			array('nama' => 'Sangkuliman', 'id_kecamatan' => '57'),
			array('nama' => 'Sari Nadi', 'id_kecamatan' => '57'),
			array('nama' => 'Sebelimbingan', 'id_kecamatan' => '57'),
			array('nama' => 'Sedulang', 'id_kecamatan' => '57'),
			array('nama' => 'Suka Bumi', 'id_kecamatan' => '57'),
			array('nama' => 'Sumber Sari', 'id_kecamatan' => '57'),
			array('nama' => 'Wonosari', 'id_kecamatan' => '57'),
			
			array('nama' => 'Bakungan', 'id_kecamatan' => '58'),
			array('nama' => 'Batuah', 'id_kecamatan' => '58'),
			array('nama' => 'Loa Duri Ilir', 'id_kecamatan' => '58'),
			array('nama' => 'Loa Duri Ulu', 'id_kecamatan' => '58'),
			array('nama' => 'Loa Janan Ulu', 'id_kecamatan' => '58'),
			array('nama' => 'Puwajaya', 'id_kecamatan' => '58'),
			array('nama' => 'Tani Bhakti', 'id_kecamatan' => '58'),
			array('nama' => 'Tani Harapan', 'id_kecamatan' => '58'),
			
			array('nama' => 'Jembayan', 'id_kecamatan' => '59'),
			array('nama' => 'Jembayan dalam', 'id_kecamatan' => '59'),
			array('nama' => 'Jembayan tengah', 'id_kecamatan' => '59'),
			array('nama' => 'Jonggon', 'id_kecamatan' => '59'),
			array('nama' => 'Jongkang', 'id_kecamatan' => '59'),
			array('nama' => 'Karya Utama', 'id_kecamatan' => '59'),
			array('nama' => 'Loa Kulu Kota', 'id_kecamatan' => '59'),
			array('nama' => 'Loh Sumber', 'id_kecamatan' => '59'),
			array('nama' => 'Lung Anai', 'id_kecamatan' => '59'),
			array('nama' => 'Marga Rahayu', 'id_kecamatan' => '59'),
			array('nama' => 'Ponoragan', 'id_kecamatan' => '59'),
			array('nama' => 'Rempanga', 'id_kecamatan' => '59'),
			array('nama' => 'Sepakat', 'id_kecamatan' => '59'),
			array('nama' => 'Sumber Sari', 'id_kecamatan' => '59'),
			array('nama' => 'Sungai Payang', 'id_kecamatan' => '59'),
			
			array('nama' => 'Bunga Putih', 'id_kecamatan' => '60'),
			array('nama' => 'Kersik', 'id_kecamatan' => '60'),
			array('nama' => 'Makarti', 'id_kecamatan' => '60'),
			array('nama' => 'Perangat Baru', 'id_kecamatan' => '60'),
			array('nama' => 'Perangat Selatan', 'id_kecamatan' => '60'),
			array('nama' => 'Sambera Baru', 'id_kecamatan' => '60'),
			array('nama' => 'Santan Ilir', 'id_kecamatan' => '60'),
			array('nama' => 'Santan Tengah', 'id_kecamatan' => '60'),
			array('nama' => 'Santan Ulu', 'id_kecamatan' => '60'),
			array('nama' => 'Sebuntal', 'id_kecamatan' => '60'),
			array('nama' => 'Semangko', 'id_kecamatan' => '60'),
			
			array('nama' => 'Badak Baru', 'id_kecamatan' => '61'),
			array('nama' => 'Badak Mekar', 'id_kecamatan' => '61'),
			array('nama' => 'Batu-Batu', 'id_kecamatan' => '61'),
			array('nama' => 'Gas Alam Badak I', 'id_kecamatan' => '61'),
			array('nama' => 'Muara Badak Ilir', 'id_kecamatan' => '61'),
			array('nama' => 'Muara Badak Ulu', 'id_kecamatan' => '61'),
			array('nama' => 'Saliki', 'id_kecamatan' => '61'),
			array('nama' => 'Salo Cella', 'id_kecamatan' => '61'),
			array('nama' => 'Salo Palai', 'id_kecamatan' => '61'),
			array('nama' => 'Suka Damai', 'id_kecamatan' => '61'),
			array('nama' => 'Sungai Bawang', 'id_kecamatan' => '61'),
			array('nama' => 'Tanah Datar', 'id_kecamatan' => '61'),
			array('nama' => 'Tanjung Limau', 'id_kecamatan' => '61'),
			
			array('nama' => 'Dondang', 'id_kecamatan' => '62'),
			array('nama' => 'Muara Jawa Ilir', 'id_kecamatan' => '62'),
			array('nama' => 'Muara Jawa Pesisir', 'id_kecamatan' => '62'),
			array('nama' => 'Muara Jawa Tengah', 'id_kecamatan' => '62'),
			array('nama' => 'Muara Jawa Ulu', 'id_kecamatan' => '62'),
			array('nama' => 'Muara Kembang', 'id_kecamatan' => '62'),
			array('nama' => 'Tama Pole', 'id_kecamatan' => '62'),
			array('nama' => 'Teluk Dalam', 'id_kecamatan' => '62'),
			
			array('nama' => 'Benua Puhun', 'id_kecamatan' => '63'),
			array('nama' => 'Bukit Jering', 'id_kecamatan' => '63'),
			array('nama' => 'Bunga Jadi', 'id_kecamatan' => '63'),
			array('nama' => 'Cipari Makmur', 'id_kecamatan' => '63'),
			array('nama' => 'Kupang Baru', 'id_kecamatan' => '63'),
			array('nama' => 'Lebaho Ulaq', 'id_kecamatan' => '63'),
			array('nama' => 'Liang Buaya', 'id_kecamatan' => '63'),
			array('nama' => 'Menamang Kanan', 'id_kecamatan' => '63'),
			array('nama' => 'Menamang Kiri', 'id_kecamatan' => '63'),
			array('nama' => 'Muara Kaman Ilir', 'id_kecamatan' => '63'),
			array('nama' => 'Muara Kaman Ulu', 'id_kecamatan' => '63'),
			array('nama' => 'Muara Siran', 'id_kecamatan' => '63'),
			array('nama' => 'Panca Jaya', 'id_kecamatan' => '63'),
			array('nama' => 'Puan Cepak', 'id_kecamatan' => '63'),
			array('nama' => 'Rantau Hempang', 'id_kecamatan' => '63'),
			array('nama' => 'Sabintulung', 'id_kecamatan' => '63'),
			array('nama' => 'Sedulang', 'id_kecamatan' => '63'),
			array('nama' => 'Sido Mukti', 'id_kecamatan' => '63'),
			array('nama' => 'Teratak', 'id_kecamatan' => '63'),
			array('nama' => 'Tunjungan', 'id_kecamatan' => '63'),
			
			array('nama' => 'Batuq', 'id_kecamatan' => '64'),
			array('nama' => 'Jantur', 'id_kecamatan' => '64'),
			array('nama' => 'Jantur Baru', 'id_kecamatan' => '64'),
			array('nama' => 'Jantur Selatan', 'id_kecamatan' => '64'),
			array('nama' => 'Kayu Batu', 'id_kecamatan' => '64'),
			array('nama' => 'Muara Aloh', 'id_kecamatan' => '64'),
			array('nama' => 'Muara Leka', 'id_kecamatan' => '64'),
			array('nama' => 'Muara Muntai Ilir', 'id_kecamatan' => '64'),
			array('nama' => 'Muara Muntai Ulu', 'id_kecamatan' => '64'),
			array('nama' => 'Perian', 'id_kecamatan' => '64'),
			array('nama' => 'Pulau Harapan', 'id_kecamatan' => '64'),
			array('nama' => 'Rebaq Rinding', 'id_kecamatan' => '64'),
			array('nama' => 'Tanjung Batuq Harapan', 'id_kecamatan' => '64'),

			array('nama' => 'Enggelam', 'id_kecamatan' => '65'),
			array('nama' => 'Lebak Cilong', 'id_kecamatan' => '65'),
			array('nama' => 'Lebaq Mantan', 'id_kecamatan' => '65'),
			array('nama' => 'Melintang', 'id_kecamatan' => '65'),
			array('nama' => 'Muara Enggelam', 'id_kecamatan' => '65'),
			array('nama' => 'Muara Wis', 'id_kecamatan' => '65'),
			array('nama' => 'Sebemban', 'id_kecamatan' => '65'),
			
			array('nama' => 'Ambarawang Darat', 'id_kecamatan' => '66'),
			array('nama' => 'Ambarawang Laut', 'id_kecamatan' => '66'),
			array('nama' => 'Argosari', 'id_kecamatan' => '66'),
			array('nama' => 'Beringin Agung', 'id_kecamatan' => '66'),
			array('nama' => 'Bukit Merdeka', 'id_kecamatan' => '66'),
			array('nama' => 'Bukit Raya', 'id_kecamatan' => '66'),
			array('nama' => 'Handil Baru', 'id_kecamatan' => '66'),
			array('nama' => 'Handil Baru Darat', 'id_kecamatan' => '66'),
			array('nama' => 'Kampung Lama', 'id_kecamatan' => '66'),
			array('nama' => 'Karya Jaya', 'id_kecamatan' => '66'),
			array('nama' => 'Karya Merdeka', 'id_kecamatan' => '66'),
			array('nama' => 'Margomulyo', 'id_kecamatan' => '66'),
			array('nama' => 'Muara Sembilang', 'id_kecamatan' => '66'),
			array('nama' => 'Salok Api Darat', 'id_kecamatan' => '66'),
			array('nama' => 'Salok Api Laut', 'id_kecamatan' => '66'),
			array('nama' => 'Samboja Kuala', 'id_kecamatan' => '66'),
			array('nama' => 'Sanipah', 'id_kecamatan' => '66'),
			array('nama' => 'Sungai Merdeka', 'id_kecamatan' => '66'),
			array('nama' => 'Sungai Seluang', 'id_kecamatan' => '66'),
			array('nama' => 'Tani Bakti', 'id_kecamatan' => '66'),
			array('nama' => 'Tanjung Harapan', 'id_kecamatan' => '66'),
			array('nama' => 'Teluk Pemedas', 'id_kecamatan' => '66'),
			array('nama' => 'Wonotirto', 'id_kecamatan' => '66'),
			
			array('nama' => 'Jawa', 'id_kecamatan' => '67'),
			array('nama' => 'Pendingin', 'id_kecamatan' => '67'),
			array('nama' => 'Sanga-Sanga Dalam', 'id_kecamatan' => '67'),
			array('nama' => 'Sanga-Sanga Muara', 'id_kecamatan' => '67'),
			array('nama' => 'Sari Jaya', 'id_kecamatan' => '67'),
			
			array('nama' => 'Baloro', 'id_kecamatan' => '68'),
			array('nama' => 'Giri Agung', 'id_kecamatan' => '68'),
			array('nama' => 'Lekaq Kidau', 'id_kecamatan' => '68'),
			array('nama' => 'Manunggal Daya', 'id_kecamatan' => '68'),
			array('nama' => 'Mekar Jaya', 'id_kecamatan' => '68'),
			array('nama' => 'Sanggulan', 'id_kecamatan' => '68'),
			array('nama' => 'Sebulu Ilir', 'id_kecamatan' => '68'),
			array('nama' => 'Sebulu Modern', 'id_kecamatan' => '68'),
			array('nama' => 'Sebulu Ulu', 'id_kecamatan' => '68'),
			array('nama' => 'Segihan', 'id_kecamatan' => '68'),
			array('nama' => 'Selerong', 'id_kecamatan' => '68'),
			array('nama' => 'Senoni', 'id_kecamatan' => '68'),
			array('nama' => 'Sumber Sari', 'id_kecamatan' => '68'),
			array('nama' => 'Tanjung Harapan', 'id_kecamatan' => '68'),

			array('nama' => 'Baru', 'id_kecamatan' => '69'),
			array('nama' => 'Bila Talang', 'id_kecamatan' => '69'),
			array('nama' => 'Buluk Sen', 'id_kecamatan' => '69'),
			array('nama' => 'Gunung Sari', 'id_kecamatan' => '69'),
			array('nama' => 'Long Lalang', 'id_kecamatan' => '69'),
			array('nama' => 'Muara Belinau', 'id_kecamatan' => '69'),
			array('nama' => 'Muara Kebaq', 'id_kecamatan' => '69'),
			array('nama' => 'Muara Pedohon', 'id_kecamatan' => '69'),
			array('nama' => 'Muara Ritan', 'id_kecamatan' => '69'),
			array('nama' => 'Muara Salung', 'id_kecamatan' => '69'),
			array('nama' => 'Muara Tiq', 'id_kecamatan' => '69'),
			array('nama' => 'Muara Tuboq', 'id_kecamatan' => '69'),
			array('nama' => 'Ritan Baru', 'id_kecamatan' => '69'),
			array('nama' => 'Sidomulyo', 'id_kecamatan' => '69'),
			array('nama' => 'Tabang Lama', 'id_kecamatan' => '69'),
			array('nama' => 'Tukung Ritan', 'id_kecamatan' => '69'),
			array('nama' => 'Umaq Bekuay', 'id_kecamatan' => '69'),
			array('nama' => 'Umaq Dian', 'id_kecamatan' => '69'),
			array('nama' => 'Umaq Tukung', 'id_kecamatan' => '69'),
			
			array('nama' => 'Bendang Raya', 'id_kecamatan' => '70'),
			array('nama' => 'Bukit Biru', 'id_kecamatan' => '70'),
			array('nama' => 'Jahab', 'id_kecamatan' => '70'),
			array('nama' => 'Kampung Baru', 'id_kecamatan' => '70'),
			array('nama' => 'Loa Ipuh', 'id_kecamatan' => '70'),
			array('nama' => 'Loa Ipuh Darat', 'id_kecamatan' => '70'),
			array('nama' => 'Loa Tebu', 'id_kecamatan' => '70'),
			array('nama' => 'Mahulu', 'id_kecamatan' => '70'),
			array('nama' => 'Mangkurawang', 'id_kecamatan' => '70'),
			array('nama' => 'Melayu', 'id_kecamatan' => '70'),
			array('nama' => 'Panji', 'id_kecamatan' => '70'),
			array('nama' => 'Rampak Lambur', 'id_kecamatan' => '70'),
			array('nama' => 'Sukarame', 'id_kecamatan' => '70'),
			array('nama' => 'Timbau', 'id_kecamatan' => '70'),
			
			array('nama' => 'Bangun Rejo', 'id_kecamatan' => '71'),
			array('nama' => 'Buana Jaya', 'id_kecamatan' => '71'),
			array('nama' => 'Bukit Pariaman', 'id_kecamatan' => '71'),
			array('nama' => 'Bukit Raya', 'id_kecamatan' => '71'),
			array('nama' => 'Embalut', 'id_kecamatan' => '71'),
			array('nama' => 'Karang Tunggal', 'id_kecamatan' => '71'),
			array('nama' => 'Kerta Buana', 'id_kecamatan' => '71'),
			array('nama' => 'Loa Lepu', 'id_kecamatan' => '71'),
			array('nama' => 'Loa Pari', 'id_kecamatan' => '71'),
			array('nama' => 'Loa Raya', 'id_kecamatan' => '71'),
			array('nama' => 'Loa Ulung', 'id_kecamatan' => '71'),
			array('nama' => 'Manunggal Jaya', 'id_kecamatan' => '71'),
			array('nama' => 'Mulawarman', 'id_kecamatan' => '71'),
			array('nama' => 'Perjiwa', 'id_kecamatan' => '71'),
			array('nama' => 'Separi', 'id_kecamatan' => '71'),
			array('nama' => 'Suka Maju', 'id_kecamatan' => '71'),
			array('nama' => 'Tanjung Batu', 'id_kecamatan' => '71'),
			array('nama' => 'Teluk Dalam', 'id_kecamatan' => '71'),

			# Kutai Timur
			array('nama' => 'Batu Timbau', 'id_kecamatan' => '72'),
			array('nama' => 'Beno Harapan', 'id_kecamatan' => '72'),
			array('nama' => 'Himba Lestari', 'id_kecamatan' => '72'),
			array('nama' => 'Mawai Indah', 'id_kecamatan' => '72'),
			array('nama' => 'Mugi Rahayu', 'id_kecamatan' => '72'),
			array('nama' => 'Telaga', 'id_kecamatan' => '72'),
			
			array('nama' => 'Keraitan', 'id_kecamatan' => '73'),
			array('nama' => 'Muara Bengalon', 'id_kecamatan' => '73'),
			array('nama' => 'Sekerat', 'id_kecamatan' => '73'),
			array('nama' => 'Sepaso', 'id_kecamatan' => '73'),
			array('nama' => 'Sepaso Barat', 'id_kecamatan' => '73'),
			array('nama' => 'Sepaso Selatan', 'id_kecamatan' => '73'),
			array('nama' => 'Sepaso Timur', 'id_kecamatan' => '73'),
			array('nama' => 'Tebangan Lebak', 'id_kecamatan' => '73'),
			array('nama' => 'Tepian Baru', 'id_kecamatan' => '73'),
			array('nama' => 'Tepian Indah', 'id_kecamatan' => '73'),
			array('nama' => 'Tepian Langsat', 'id_kecamatan' => '73'),
			
			array('nama' => 'Long Betuq', 'id_kecamatan' => '74'),
			array('nama' => 'Long Lees', 'id_kecamatan' => '74'),
			array('nama' => 'Long Nyelong', 'id_kecamatan' => '74'),
			array('nama' => 'Long Pejeng', 'id_kecamatan' => '74'),
			array('nama' => 'Mekar Baru', 'id_kecamatan' => '74'),
			array('nama' => 'Rantau Sentosa', 'id_kecamatan' => '74'),
			
			array('nama' => 'Bangun Jaya', 'id_kecamatan' => '75'),
			array('nama' => 'Bukit Harapan', 'id_kecamatan' => '75'),
			array('nama' => 'Bukit Makmur', 'id_kecamatan' => '75'),
			array('nama' => 'Bumi Sejahtera', 'id_kecamatan' => '75'),
			array('nama' => 'Citra Manunggal Jaya', 'id_kecamatan' => '75'),
			array('nama' => 'Kaliorang', 'id_kecamatan' => '75'),
			array('nama' => 'Selangkau', 'id_kecamatan' => '75'),
			
			array('nama' => "Ba'ay", 'id_kecamatan' => '76'),
			array('nama' => 'Batu Lepoq', 'id_kecamatan' => '76'),
			array('nama' => 'Karangan Dalam', 'id_kecamatan' => '76'),
			array('nama' => 'Karangan Hilir', 'id_kecamatan' => '76'),
			array('nama' => 'Karangan Seberang', 'id_kecamatan' => '76'),
			array('nama' => 'Mukti Lestari', 'id_kecamatan' => '76'),
			array('nama' => 'Pengadan', 'id_kecamatan' => '76'),

			array('nama' => 'Bukit Permata', 'id_kecamatan' => '77'),
			array('nama' => 'Bumi Etam', 'id_kecamatan' => '77'),
			array('nama' => 'Bumi Jaya', 'id_kecamatan' => '77'),
			array('nama' => 'Bumi Rapak', 'id_kecamatan' => '77'),
			array('nama' => 'Cipta Graha', 'id_kecamatan' => '77'),
			array('nama' => 'Kadungan Jaya', 'id_kecamatan' => '77'),
			array('nama' => 'Mata Air', 'id_kecamatan' => '77'),
			array('nama' => 'Pengadan Baru', 'id_kecamatan' => '77'),
			
			array('nama' => 'Kombeng Indah', 'id_kecamatan' => '78'),
			array('nama' => 'Makmur Jaya', 'id_kecamatan' => '78'),
			array('nama' => 'Marga Mulya', 'id_kecamatan' => '78'),
			array('nama' => 'Miau Baru', 'id_kecamatan' => '78'),
			array('nama' => 'Sidomulyo', 'id_kecamatan' => '78'),
			array('nama' => 'Sri Pantun', 'id_kecamatan' => '78'),
			array('nama' => 'Sukamaju', 'id_kecamatan' => '78'),
			
			array('nama' => 'Melan', 'id_kecamatan' => '79'),
			array('nama' => 'Mukti Utama', 'id_kecamatan' => '79'),
			array('nama' => 'Segoi Makmur', 'id_kecamatan' => '79'),
			array('nama' => 'Sika Makmur', 'id_kecamatan' => '79'),
			array('nama' => 'Sumber Agung', 'id_kecamatan' => '79'),
			array('nama' => 'Sumber Sari', 'id_kecamatan' => '79'),
			array('nama' => 'Tanah Abang', 'id_kecamatan' => '79'),
			
			array('nama' => 'Gemar Baru', 'id_kecamatan' => '80'),
			array('nama' => 'Kelinjau Ilir', 'id_kecamatan' => '80'),
			array('nama' => 'Kelinjau Ulu', 'id_kecamatan' => '80'),
			array('nama' => 'Long Nah', 'id_kecamatan' => '80'),
			array('nama' => 'Long Poq Baru', 'id_kecamatan' => '80'),
			array('nama' => 'Long Tesak', 'id_kecamatan' => '80'),
			array('nama' => 'Muara Dun', 'id_kecamatan' => '80'),
			array('nama' => 'Senyiur', 'id_kecamatan' => '80'),

			array('nama' => 'Batu Balai', 'id_kecamatan' => '81'),
			array('nama' => 'Benua Baru', 'id_kecamatan' => '81'),
			array('nama' => 'Muara Bengkal Ilir', 'id_kecamatan' => '81'),
			array('nama' => 'Muara Bengkal Ulu', 'id_kecamatan' => '81'),
			array('nama' => 'Mulupan', 'id_kecamatan' => '81'),
			array('nama' => 'Ngayau', 'id_kecamatan' => '81'),
			array('nama' => 'Senambah', 'id_kecamatan' => '81'),
			
			array('nama' => 'Benhes', 'id_kecamatan' => '82'),
			array('nama' => 'Babeq', 'id_kecamatan' => '82'),
			array('nama' => 'Diaq Lay', 'id_kecamatan' => '82'),
			array('nama' => 'Juk Luay', 'id_kecamatan' => '82'),
			array('nama' => 'Karya Bhakti', 'id_kecamatan' => '82'),
			array('nama' => 'Long Wehea', 'id_kecamatan' => '82'),
			array('nama' => 'Muara Wahau', 'id_kecamatan' => '82'),
			array('nama' => 'Nehes Liah Bing', 'id_kecamatan' => '82'),
			array('nama' => 'Wahau Baru', 'id_kecamatan' => '82'),
			array('nama' => 'Wanasari', 'id_kecamatan' => '82'),
			
			array('nama' => 'Kebon Agung', 'id_kecamatan' => '83'),
			array('nama' => 'Manunggal Jaya', 'id_kecamatan' => '83'),
			array('nama' => 'Margo Mulyo', 'id_kecamatan' => '83'),
			array('nama' => 'Mukti Jaya', 'id_kecamatan' => '83'),
			array('nama' => 'Pulung Sari', 'id_kecamatan' => '83'),
			array('nama' => 'Rantau Makmur', 'id_kecamatan' => '83'),
			array('nama' => 'Tanjung Labu', 'id_kecamatan' => '83'),
			array('nama' => 'Tepian Makmur', 'id_kecamatan' => '83'),
			
			array('nama' => 'Manubar', 'id_kecamatan' => '84'),
			array('nama' => 'Marukangan', 'id_kecamatan' => '84'),
			array('nama' => 'Sandaran', 'id_kecamatan' => '84'),
			array('nama' => 'Susuk Dalam', 'id_kecamatan' => '84'),
			array('nama' => 'Susuk Luar', 'id_kecamatan' => '84'),
			array('nama' => 'Tadoan', 'id_kecamatan' => '84'),
			array('nama' => 'Tanjung Mangkalihat', 'id_kecamatan' => '84'),
			
			array('nama' => 'Sangatta Selatan', 'id_kecamatan' => '85'),
			array('nama' => 'Sangkima', 'id_kecamatan' => '85'),
			array('nama' => 'Sangkima Lama', 'id_kecamatan' => '85'),
			array('nama' => 'Singa Geweh', 'id_kecamatan' => '85'),
			
			array('nama' => 'Sangatta Utara', 'id_kecamatan' => '86'),
			array('nama' => 'Singa Gembara', 'id_kecamatan' => '86'),
			array('nama' => 'Swarga Bara', 'id_kecamatan' => '86'),
			array('nama' => 'Teluk Lingga', 'id_kecamatan' => '86'),
			
			array('nama' => 'Benua Baru Ili', 'id_kecamatan' => '87'),
			array('nama' => 'Benua Baru Ulu', 'id_kecamatan' => '87'),
			array('nama' => 'Kerayaan', 'id_kecamatan' => '87'),
			array('nama' => 'Kolek', 'id_kecamatan' => '87'),
			array('nama' => 'Maloy', 'id_kecamatan' => '87'),
			array('nama' => 'Mandau Pantai Sejahtera', 'id_kecamatan' => '87'),
			array('nama' => 'Mandu Dalam', 'id_kecamatan' => '87'),
			array('nama' => 'Pelawan', 'id_kecamatan' => '87'),
			array('nama' => 'Peridan', 'id_kecamatan' => '87'),
			array('nama' => 'Perupuk', 'id_kecamatan' => '87'),
			array('nama' => 'Pulau Miang', 'id_kecamatan' => '87'),
			array('nama' => 'Saqa', 'id_kecamatan' => '87'),
			array('nama' => 'Sempayau', 'id_kecamatan' => '87'),
			array('nama' => 'Tanjung Manis', 'id_kecamatan' => '87'),
			array('nama' => 'Tepian Tarap', 'id_kecamatan' => '87'),
			
			array('nama' => 'Juk Ayaq', 'id_kecamatan' => '88'),
			array('nama' => 'Long Melah', 'id_kecamatan' => '88'),
			array('nama' => 'Long Noran', 'id_kecamatan' => '88'),
			array('nama' => 'Long Segar', 'id_kecamatan' => '88'),
			array('nama' => 'Marah Haloq', 'id_kecamatan' => '88'),
			array('nama' => 'Muara Pantun', 'id_kecamatan' => '88'),
			array('nama' => 'Rantau Panjang', 'id_kecamatan' => '88'),
			
			array('nama' => 'Danau Redan', 'id_kecamatan' => '89'),
			array('nama' => 'Kandolo', 'id_kecamatan' => '89'),
			array('nama' => 'Martadinata', 'id_kecamatan' => '89'),
			array('nama' => 'Suka Rahmat', 'id_kecamatan' => '89'),
			array('nama' => 'Teluk Pandan', 'id_kecamatan' => '89'),

			# Malinau
			array('nama' => 'Apau Ping', 'id_kecamatan' => '90'),
			array('nama' => 'Long Alango', 'id_kecamatan' => '90'),
			array('nama' => 'Long Berini', 'id_kecamatan' => '90'),
			array('nama' => 'Long Kemuat', 'id_kecamatan' => '90'),
			array('nama' => 'Long Tebula', 'id_kecamatan' => '90'),
			array('nama' => 'Long Uli', 'id_kecamatan' => '90'),
			
			array('nama' => 'Data Dian', 'id_kecamatan' => '91'),
			array('nama' => 'Long Meitun', 'id_kecamatan' => '91'),
			array('nama' => 'Long Pipa', 'id_kecamatan' => '91'),
			array('nama' => 'Long Sule', 'id_kecamatan' => '91'),
			array('nama' => 'Sungai Anai', 'id_kecamatan' => '91'),
			
			array('nama' => 'Long Betoah', 'id_kecamatan' => '92'),
			array('nama' => 'Long Nawang', 'id_kecamatan' => '92'),
			array('nama' => 'Long Payau', 'id_kecamatan' => '92'),
			array('nama' => 'Long Temuyat', 'id_kecamatan' => '92'),
			array('nama' => 'Nawang Baru', 'id_kecamatan' => '92'),

			array('nama' => 'Lidung Payau', 'id_kecamatan' => '93'),
			array('nama' => 'Long Ampung', 'id_kecamatan' => '93'),
			array('nama' => 'Long Uro', 'id_kecamatan' => '93'),
			array('nama' => 'Metulang', 'id_kecamatan' => '93'),
			array('nama' => 'Sungai Barang', 'id_kecamatan' => '93'),
			
			array('nama' => 'Kuala Lapang', 'id_kecamatan' => '94'),
			array('nama' => 'Long Bila', 'id_kecamatan' => '94'),
			array('nama' => 'Long Kenipe', 'id_kecamatan' => '94'),
			array('nama' => 'Punan Bengalun', 'id_kecamatan' => '94'),
			array('nama' => 'Sempayang', 'id_kecamatan' => '94'),
			array('nama' => 'Sentaban', 'id_kecamatan' => '94'),
			array('nama' => 'Sesua', 'id_kecamatan' => '94'),
			array('nama' => 'Tanjung Lapang', 'id_kecamatan' => '94'),
			array('nama' => 'Taras', 'id_kecamatan' => '94'),
			
			array('nama' => 'Batu Lidung', 'id_kecamatan' => '95'),
			array('nama' => 'Malinau Hilir', 'id_kecamatan' => '95'),
			array('nama' => 'Malinau Hulu', 'id_kecamatan' => '95'),
			array('nama' => 'Malinau Kota', 'id_kecamatan' => '95'),
			array('nama' => 'Pelita Kanaan', 'id_kecamatan' => '95'),
			array('nama' => 'Tanjung Keranjang', 'id_kecamatan' => '95'),
			
			array('nama' => 'Bila Bekayung', 'id_kecamatan' => '96'),
			array('nama' => 'Laban Nyarit', 'id_kecamatan' => '96'),
			array('nama' => 'Langkap', 'id_kecamatan' => '96'),
			array('nama' => 'Long Loreh', 'id_kecamatan' => '96'),
			array('nama' => 'Nunuk Tanah Kibang', 'id_kecamatan' => '96'),
			array('nama' => 'Paya Seturan', 'id_kecamatan' => '96'),
			array('nama' => 'Pelencau', 'id_kecamatan' => '96'),
			array('nama' => 'Punan Rian', 'id_kecamatan' => '96'),
			array('nama' => 'Sengayan', 'id_kecamatan' => '96'),
			
			array('nama' => 'Batu Kajang', 'id_kecamatan' => '97'),
			array('nama' => 'Gong Solok', 'id_kecamatan' => '97'),
			array('nama' => 'Long Adiu', 'id_kecamatan' => '97'),
			array('nama' => 'Punan Gong Solok', 'id_kecamatan' => '97'),
			array('nama' => 'Punan Long Adiu', 'id_kecamatan' => '97'),
			array('nama' => 'Punan Setarap', 'id_kecamatan' => '97'),
			array('nama' => 'Setarap', 'id_kecamatan' => '97'),
			array('nama' => 'Setulang', 'id_kecamatan' => '97'),
			
			array('nama' => 'Halanga', 'id_kecamatan' => '98'),
			array('nama' => 'Long Jalan', 'id_kecamatan' => '98'),
			array('nama' => 'Long Lake', 'id_kecamatan' => '98'),
			array('nama' => 'Long Rat', 'id_kecamatan' => '98'),
			array('nama' => 'Metut', 'id_kecamatan' => '98'),
			array('nama' => 'Nahakramo Baru', 'id_kecamatan' => '98'),
			array('nama' => 'Punan Mirau', 'id_kecamatan' => '98'),
			array('nama' => 'Tanjung Nanga', 'id_kecamatan' => '98'),
			
			array('nama' => 'Belayan', 'id_kecamatan' => '99'),
			array('nama' => 'Kaliamok', 'id_kecamatan' => '99'),
			array('nama' => 'Kelapis', 'id_kecamatan' => '99'),
			array('nama' => 'Lubak Manis', 'id_kecamatan' => '99'),
			array('nama' => 'Luso', 'id_kecamatan' => '99'),
			array('nama' => 'Malinau Seberang', 'id_kecamatan' => '99'),
			array('nama' => 'Putat', 'id_kecamatan' => '99'),
			array('nama' => 'Ruspen Tubu', 'id_kecamatan' => '99'),
			array('nama' => 'Salap', 'id_kecamatan' => '99'),
			array('nama' => 'Sembuak Warod', 'id_kecamatan' => '99'),
			array('nama' => 'Semengaris', 'id_kecamatan' => '99'),
			array('nama' => 'Seruyung', 'id_kecamatan' => '99'),
			
			array('nama' => 'Harapan Maju', 'id_kecamatan' => '100'),
			array('nama' => 'Lidung Kemenci', 'id_kecamatan' => '100'),
			array('nama' => 'Long Bisai', 'id_kecamatan' => '100'),
			array('nama' => 'Long Gafid', 'id_kecamatan' => '100'),
			array('nama' => 'Long Liku', 'id_kecamatan' => '100'),
			array('nama' => 'Mentarang Baru', 'id_kecamatan' => '100'),
			array('nama' => 'Paking', 'id_kecamatan' => '100'),
			array('nama' => 'Pulau Sapi', 'id_kecamatan' => '100'),
			array('nama' => 'Temalang', 'id_kecamatan' => '100'),
			
			array('nama' => 'Long Berang', 'id_kecamatan' => '101'),
			array('nama' => 'Long Kebinu', 'id_kecamatan' => '101'),
			array('nama' => 'Long Mekatip', 'id_kecamatan' => '101'),
			array('nama' => 'Long Pala', 'id_kecamatan' => '101'),
			array('nama' => 'Long Semamu', 'id_kecamatan' => '101'),
			array('nama' => 'Long Simau', 'id_kecamatan' => '101'),
			array('nama' => 'Long Sulit', 'id_kecamatan' => '101'),
			
			array('nama' => 'Lame', 'id_kecamatan' => '102'),
			array('nama' => 'Long Aran', 'id_kecamatan' => '102'),
			array('nama' => 'Long Belaka Pitau', 'id_kecamatan' => '102'),
			array('nama' => 'Long Bena', 'id_kecamatan' => '102'),
			array('nama' => 'Long Jelet', 'id_kecamatan' => '102'),
			array('nama' => 'Long Ketaman', 'id_kecamatan' => '102'),
			array('nama' => 'Long Paliran', 'id_kecamatan' => '102'),
			array('nama' => 'Long Pua', 'id_kecamatan' => '102'),
			array('nama' => 'Long Pujungan', 'id_kecamatan' => '102'),
			
			array('nama' => 'Agung Baru', 'id_kecamatan' => '103'),
			array('nama' => 'Data Baru', 'id_kecamatan' => '103'),
			array('nama' => 'Dumu Mahak', 'id_kecamatan' => '103'),
			array('nama' => 'Long Tebusan', 'id_kecamatan' => '103'),
			array('nama' => 'Long Top', 'id_kecamatan' => '103'),
			array('nama' => 'Mahak Baru', 'id_kecamatan' => '103'),
			
			array('nama' => 'Long Nyau', 'id_kecamatan' => '104'),
			array('nama' => 'Long Pada', 'id_kecamatan' => '104'),
			array('nama' => 'Long Ranau', 'id_kecamatan' => '104'),
			array('nama' => 'Long Titi', 'id_kecamatan' => '104'),
			array('nama' => 'Rian Tubu', 'id_kecamatan' => '104'),

		);

		$temp3 = array(

			# Nunukan
			array('nama' => 'Ba Sikor', 'id_kecamatan' => '105'),
			array('nama' => 'Buduk Kinangan', 'id_kecamatan' => '105'),
			array('nama' => 'Buduk Kubul', 'id_kecamatan' => '105'),
			array('nama' => 'Buduk Tumu', 'id_kecamatan' => '105'),
			array('nama' => 'Bungayan', 'id_kecamatan' => '105'),
			array('nama' => 'Cinglat', 'id_kecamatan' => '105'),
			array('nama' => 'Kampung Baru', 'id_kecamatan' => '105'),
			array('nama' => 'Lembada', 'id_kecamatan' => '105'),
			array('nama' => 'Lembudud', 'id_kecamatan' => '105'),
			array('nama' => 'Lepatar', 'id_kecamatan' => '105'),
			array('nama' => 'Liang Aliq', 'id_kecamatan' => '105'),
			array('nama' => 'Liang Biadung', 'id_kecamatan' => '105'),
			array('nama' => 'Liang Bua', 'id_kecamatan' => '105'),
			array('nama' => 'Liang Butan', 'id_kecamatan' => '105'),
			array('nama' => 'Liang Tuer', 'id_kecamatan' => '105'),
			array('nama' => 'Liang Turan', 'id_kecamatan' => '105'),
			array('nama' => 'Long Bawan', 'id_kecamatan' => '105'),
			array('nama' => 'Long Berayang', 'id_kecamatan' => '105'),
			array('nama' => 'Long Kabid', 'id_kecamatan' => '105'),
			array('nama' => 'Long Katung', 'id_kecamatan' => '105'),
			array('nama' => 'Long Mangan', 'id_kecamatan' => '105'),
			array('nama' => 'Long Matung', 'id_kecamatan' => '105'),
			array('nama' => 'Long Nawan', 'id_kecamatan' => '105'),
			array('nama' => 'Long Nawang', 'id_kecamatan' => '105'),
			array('nama' => 'Long Nuat', 'id_kecamatan' => '105'),
			array('nama' => 'Long Puak', 'id_kecamatan' => '105'),
			array('nama' => 'Long Rupan', 'id_kecamatan' => '105'),
			array('nama' => 'Long Sepayang', 'id_kecamatan' => '105'),
			array('nama' => 'Long Tenem', 'id_kecamatan' => '105'),
			array('nama' => 'Long Tugul', 'id_kecamatan' => '105'),
			array('nama' => 'Long Umung', 'id_kecamatan' => '105'),
			array('nama' => "Ma'Libu", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Api", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Betung", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Butal", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Delung", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Inan", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Kebuan", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Kemut", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Kidang", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Lidung", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Lutut", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Matung", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Melade", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Mering", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Mulak", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Nado", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Padi", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Pala", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Pani", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Pawan", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Payak", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Pirit", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Putuk", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Rangeb", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Raye", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Rupai", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Sire", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Terutun", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Umung", 'id_kecamatan' => '105'),
			array('nama' => "Pa'Urud", 'id_kecamatan' => '105'),
			array('nama' => 'Sembudud', 'id_kecamatan' => '105'),
			array('nama' => 'Sinar Baru', 'id_kecamatan' => '105'),
			array('nama' => "Wa'Laya", 'id_kecamatan' => '105'),
			array('nama' => "Wa'Yagung", 'id_kecamatan' => '105'),
			array('nama' => "Wa'Yanud", 'id_kecamatan' => '105'),
			
			array('nama' => "Ba' Likung", 'id_kecamatan' => '106'),
			array('nama' => 'Binuang', 'id_kecamatan' => '106'),
			array('nama' => 'Liang Lanuk', 'id_kecamatan' => '106'),
			array('nama' => 'Long Birar', 'id_kecamatan' => '106'),
			array('nama' => 'Long Budung', 'id_kecamatan' => '106'),
			array('nama' => 'Long Klupan', 'id_kecamatan' => '106'),
			array('nama' => 'Long Mutan', 'id_kecamatan' => '106'),
			array('nama' => 'Long Padi', 'id_kecamatan' => '106'),
			array('nama' => 'Long Pasia', 'id_kecamatan' => '106'),
			array('nama' => 'Long Pupung', 'id_kecamatan' => '106'),
			array('nama' => 'Long Rian', 'id_kecamatan' => '106'),
			array('nama' => 'Long Rungan', 'id_kecamatan' => '106'),
			array('nama' => "Pa' Amai", 'id_kecamatan' => '106'),
			array('nama' => "Pa' Dalan", 'id_kecamatan' => '106'),
			array('nama' => "Pa' Ibang", 'id_kecamatan' => '106'),
			array('nama' => "Pa' Kaber", 'id_kecamatan' => '106'),
			array('nama' => "Pa'Milau", 'id_kecamatan' => '106'),
			array('nama' => "Pa' Sing", 'id_kecamatan' => '106'),
			array('nama' => "Pa' Tera", 'id_kecamatan' => '106'),
			array('nama' => "Pa' Upan", 'id_kecamatan' => '106'),
			array('nama' => "Pa' Urang", 'id_kecamatan' => '106'),
			array('nama' => "Pa' Yalau", 'id_kecamatan' => '106'),
			array('nama' => 'Tang Badui', 'id_kecamatan' => '106'),
			array('nama' => 'Tang Paye', 'id_kecamatan' => '106'),
			
			array('nama' => 'Bulan Bulan', 'id_kecamatan' => '107'),
			array('nama' => 'Dabulon', 'id_kecamatan' => '107'),
			array('nama' => 'Deralon', 'id_kecamatan' => '107'),
			array('nama' => 'Kalampising', 'id_kecamatan' => '107'),
			array('nama' => 'Liang', 'id_kecamatan' => '107'),
			array('nama' => 'Libang', 'id_kecamatan' => '107'),
			array('nama' => 'Likos', 'id_kecamatan' => '107'),
			array('nama' => 'Lintong', 'id_kecamatan' => '107'),
			array('nama' => 'Mansalong', 'id_kecamatan' => '107'),
			array('nama' => 'Nainsid', 'id_kecamatan' => '107'),
			array('nama' => "Pa'Lemumut", 'id_kecamatan' => '107'),
			array('nama' => "Pa'Loo", 'id_kecamatan' => '107'),
			array('nama' => 'Patal I', 'id_kecamatan' => '107'),
			array('nama' => 'Patal II', 'id_kecamatan' => '107'),
			array('nama' => 'Podong', 'id_kecamatan' => '107'),
			array('nama' => 'Pulu Bulawan', 'id_kecamatan' => '107'),
			array('nama' => 'Saludan', 'id_kecamatan' => '107'),
			array('nama' => 'Sangkub', 'id_kecamatan' => '107'),
			array('nama' => 'Sapunyan', 'id_kecamatan' => '107'),
			array('nama' => 'Sasibu', 'id_kecamatan' => '107'),
			array('nama' => 'Sedengon', 'id_kecamatan' => '107'),
			array('nama' => 'Semalat', 'id_kecamatan' => '107'),
			array('nama' => 'Siawang', 'id_kecamatan' => '107'),
			array('nama' => 'Sumalumung', 'id_kecamatan' => '107'),
			array('nama' => 'Taluan', 'id_kecamatan' => '107'),
			array('nama' => 'Tanjung Hilir', 'id_kecamatan' => '107'),
			array('nama' => 'Tanjung Hulu', 'id_kecamatan' => '107'),
			array('nama' => 'Tubus', 'id_kecamatan' => '107'),
			
			array('nama' => 'Batung', 'id_kecamatan' => '108'),
			array('nama' => 'Bokok', 'id_kecamatan' => '108'),
			array('nama' => 'Bulu Mengolom', 'id_kecamatan' => '108'),
			array('nama' => 'Bululaun Hilir', 'id_kecamatan' => '108'),
			array('nama' => 'Bululaun Hulu', 'id_kecamatan' => '108'),
			array('nama' => 'Duyan', 'id_kecamatan' => '108'),
			array('nama' => 'Jukup', 'id_kecamatan' => '108'),
			array('nama' => 'Kabungolor', 'id_kecamatan' => '108'),
			array('nama' => 'Kalambuku', 'id_kecamatan' => '108'),
			array('nama' => 'Kalisun', 'id_kecamatan' => '108'),
			array('nama' => 'Kuyo', 'id_kecamatan' => '108'),
			array('nama' => 'Labang', 'id_kecamatan' => '108'),
			array('nama' => 'Labuk', 'id_kecamatan' => '108'),
			array('nama' => 'Lagas', 'id_kecamatan' => '108'),
			array('nama' => 'Langgason', 'id_kecamatan' => '108'),
			array('nama' => 'Limpakon', 'id_kecamatan' => '108'),
			array('nama' => 'Linsayung', 'id_kecamatan' => '108'),
			array('nama' => 'Lipaga', 'id_kecamatan' => '108'),
			array('nama' => 'Long Bulu', 'id_kecamatan' => '108'),
			array('nama' => 'Mamasin', 'id_kecamatan' => '108'),
			array('nama' => 'Nansapan', 'id_kecamatan' => '108'),
			array('nama' => 'Nantuidan', 'id_kecamatan' => '108'),
			array('nama' => 'Ngawol', 'id_kecamatan' => '108'),
			array('nama' => 'Paluan', 'id_kecamatan' => '108'),
			array('nama' => 'Panas', 'id_kecamatan' => '108'),
			array('nama' => 'Payang', 'id_kecamatan' => '108'),
			array('nama' => 'Salan', 'id_kecamatan' => '108'),
			array('nama' => 'Samunti', 'id_kecamatan' => '108'),
			array('nama' => 'Sanal', 'id_kecamatan' => '108'),
			array('nama' => 'Sedalit', 'id_kecamatan' => '108'),
			array('nama' => 'Semata', 'id_kecamatan' => '108'),
			array('nama' => 'Sibalu', 'id_kecamatan' => '108'),
			array('nama' => 'Sinampila I', 'id_kecamatan' => '108'),
			array('nama' => 'Sinampila II', 'id_kecamatan' => '108'),
			array('nama' => 'Sumantipal', 'id_kecamatan' => '108'),
			array('nama' => 'Sumentobol', 'id_kecamatan' => '108'),
			array('nama' => 'Sungoi', 'id_kecamatan' => '108'),
			array('nama' => 'Suyadon', 'id_kecamatan' => '108'),
			array('nama' => 'Tadungus', 'id_kecamatan' => '108'),
			array('nama' => 'Tambalang Hilir', 'id_kecamatan' => '108'),
			array('nama' => 'Tambalang Hulu', 'id_kecamatan' => '108'),
			array('nama' => 'Tantalujuk', 'id_kecamatan' => '108'),
			array('nama' => 'Tau Lumbis', 'id_kecamatan' => '108'),
			array('nama' => 'Tetagas', 'id_kecamatan' => '108'),
			array('nama' => 'Tukulon', 'id_kecamatan' => '108'),
			array('nama' => 'Tumantalas', 'id_kecamatan' => '108'),
			array('nama' => 'Tuntulibing', 'id_kecamatan' => '108'),
			array('nama' => 'Ubol Alung', 'id_kecamatan' => '108'),
			array('nama' => 'Ubol Sulok', 'id_kecamatan' => '108'),
			
			array('nama' => 'Binusan', 'id_kecamatan' => '109'),
			array('nama' => 'Nunukan Barat', 'id_kecamatan' => '109'),
			array('nama' => 'Nunukan Tengah', 'id_kecamatan' => '109'),
			array('nama' => 'Nunukan Timur', 'id_kecamatan' => '109'),
			array('nama' => 'Nunukan Utara', 'id_kecamatan' => '109'),
			
			array('nama' => 'Mansapa', 'id_kecamatan' => '110'),
			array('nama' => 'Nunuka Selatan', 'id_kecamatan' => '110'),
			array('nama' => 'Selisun', 'id_kecamatan' => '110'),
			array('nama' => 'Tanjung Harapan', 'id_kecamatan' => '110'),
			
			array('nama' => 'Balan Siku', 'id_kecamatan' => '111'),
			array('nama' => 'Bukit Aru Indah', 'id_kecamatan' => '111'),
			array('nama' => 'Padaidi', 'id_kecamatan' => '111'),
			array('nama' => 'Pancang', 'id_kecamatan' => '111'),
			array('nama' => 'Sei Manurung', 'id_kecamatan' => '111'),
			array('nama' => 'Sungai Nyamuk', 'id_kecamatan' => '111'),
			array('nama' => 'Tanjung Aru', 'id_kecamatan' => '111'),
			array('nama' => 'Tanjung Karang', 'id_kecamatan' => '111'),
			
			array('nama' => 'Aji Kuning', 'id_kecamatan' => '112'),
			array('nama' => 'Bambangan', 'id_kecamatan' => '112'),
			array('nama' => 'Binalawan', 'id_kecamatan' => '112'),
			array('nama' => 'Liang Bunyu', 'id_kecamatan' => '112'),
			array('nama' => 'Maspul', 'id_kecamatan' => '112'),
			array('nama' => 'Setabu', 'id_kecamatan' => '112'),
			array('nama' => 'Sungai Limau', 'id_kecamatan' => '112'),
			
			array('nama' => 'Aji Kuning', 'id_kecamatan' => '113'),
			array('nama' => 'Bukit Harapan', 'id_kecamatan' => '113'),
			array('nama' => 'Maspul', 'id_kecamatan' => '113'),
			array('nama' => 'Sei Limau', 'id_kecamatan' => '113'),
			
			array('nama' => 'Bukit Aru Indah', 'id_kecamatan' => '114'),
			array('nama' => 'Sei Nyamuk', 'id_kecamatan' => '114'),
			array('nama' => 'Tanjung Aru', 'id_kecamatan' => '114'),
			array('nama' => 'Tanjung Harapan', 'id_kecamatan' => '114'),
			
			array('nama' => 'Lapri', 'id_kecamatan' => '115'),
			array('nama' => 'Seberang', 'id_kecamatan' => '115'),
			array('nama' => 'Sei Pancang', 'id_kecamatan' => '115'),
			
			array('nama' => 'Apas', 'id_kecamatan' => '116'),
			array('nama' => 'Balatikon', 'id_kecamatan' => '116'),
			array('nama' => 'Bebanas', 'id_kecamatan' => '116'),
			array('nama' => 'Harapan', 'id_kecamatan' => '116'),
			array('nama' => 'Kalunsayan', 'id_kecamatan' => '116'),
			array('nama' => 'Kekayap', 'id_kecamatan' => '116'),
			array('nama' => 'Kunyit', 'id_kecamatan' => '116'),
			array('nama' => 'Lulu', 'id_kecamatan' => '116'),
			array('nama' => 'Makmur', 'id_kecamatan' => '116'),
			array('nama' => 'Melasu Baru', 'id_kecamatan' => '116'),
			array('nama' => 'Naputi', 'id_kecamatan' => '116'),
			array('nama' => 'Pembeliangan', 'id_kecamatan' => '116'),
			array('nama' => 'Sanur', 'id_kecamatan' => '116'),
			array('nama' => 'Sekikilan', 'id_kecamatan' => '116'),
			array('nama' => 'Semunat', 'id_kecamatan' => '116'),
			array('nama' => 'Sujau', 'id_kecamatan' => '116'),
			array('nama' => 'Tau Baru', 'id_kecamatan' => '116'),
			array('nama' => 'Tembalang', 'id_kecamatan' => '116'),
			array('nama' => 'Tetaban', 'id_kecamatan' => '116'),
			array('nama' => 'Tinampak I', 'id_kecamatan' => '116'),
			array('nama' => 'Tinampak II', 'id_kecamatan' => '116'),
			
			array('nama' => 'Samaenre Semaja', 'id_kecamatan' => '117'),
			array('nama' => 'Sekaduyan Taka', 'id_kecamatan' => '117'),
			array('nama' => 'Srinanti', 'id_kecamatan' => '117'),
			array('nama' => 'Tabur Lestari', 'id_kecamatan' => '117'),
			
			array('nama' => 'Atap', 'id_kecamatan' => '118'),
			array('nama' => 'Binanun', 'id_kecamatan' => '118'),
			array('nama' => 'Butas Bagu', 'id_kecamatan' => '118'),
			array('nama' => 'Katul', 'id_kecamatan' => '118'),
			array('nama' => 'Labuk', 'id_kecamatan' => '118'),
			array('nama' => 'Liuk BulU', 'id_kecamatan' => '118'),
			array('nama' => 'Lubakan', 'id_kecamatan' => '118'),
			array('nama' => 'Lubok Buat', 'id_kecamatan' => '118'),
			array('nama' => 'Mambulu', 'id_kecamatan' => '118'),
			array('nama' => 'Manuk Bangkul', 'id_kecamatan' => '118'),
			array('nama' => 'Pagaluyon', 'id_kecamatan' => '118'),
			array('nama' => 'Pagar', 'id_kecamatan' => '118'),
			array('nama' => 'Pelaju', 'id_kecamatan' => '118'),
			array('nama' => 'Pulau Keras', 'id_kecamatan' => '118'),
			array('nama' => 'Sabuluan', 'id_kecamatan' => '118'),
			array('nama' => 'Saduman', 'id_kecamatan' => '118'),
			array('nama' => 'Tagul', 'id_kecamatan' => '118'),
			array('nama' => 'Tepian', 'id_kecamatan' => '118'),
			array('nama' => 'Tujung', 'id_kecamatan' => '118'),
			array('nama' => 'Tulang', 'id_kecamatan' => '118'),
			
			array('nama' => 'Balatikon', 'id_kecamatan' => '119'),
			array('nama' => 'Kelun Sayan', 'id_kecamatan' => '119'),
			array('nama' => 'Makmur', 'id_kecamatan' => '119'),
			array('nama' => 'Naputi', 'id_kecamatan' => '119'),
			array('nama' => 'Salang', 'id_kecamatan' => '119'),
			array('nama' => 'Sanur', 'id_kecamatan' => '119'),
			array('nama' => 'Sekikilan', 'id_kecamatan' => '119'),
			array('nama' => 'Semunad', 'id_kecamatan' => '119'),
			array('nama' => 'Tau Baru', 'id_kecamatan' => '119'),
			array('nama' => 'Tembalang', 'id_kecamatan' => '119'),
			array('nama' => 'Tinampak I', 'id_kecamatan' => '119'),
			array('nama' => 'Tinampak II', 'id_kecamatan' => '119'),

			# Paser
			array('nama' => 'Bai Jaya', 'id_kecamatan' => '120'),
			array('nama' => 'Kerang', 'id_kecamatan' => '120'),
			array('nama' => 'Kerang Dayo', 'id_kecamatan' => '120'),
			array('nama' => 'Langgai', 'id_kecamatan' => '120'),
			array('nama' => 'Lomu', 'id_kecamatan' => '120'),
			array('nama' => 'Mengkudu', 'id_kecamatan' => '120'),
			array('nama' => 'Pengguren Jaya', 'id_kecamatan' => '120'),
			array('nama' => 'Petangis', 'id_kecamatan' => '120'),
			array('nama' => 'Riwang', 'id_kecamatan' => '120'),
			array('nama' => 'Saing Prupuk', 'id_kecamatan' => '120'),
			array('nama' => 'Segendang', 'id_kecamatan' => '120'),
			array('nama' => 'Tembu Paser Damai', 'id_kecamatan' => '120'),
			array('nama' => 'Tempakan', 'id_kecamatan' => '120'),
			
			array('nama' => 'Batu Kajang', 'id_kecamatan' => '121'),
			array('nama' => 'Busui', 'id_kecamatan' => '121'),
			array('nama' => 'Kasungai', 'id_kecamatan' => '121'),
			array('nama' => 'Legai', 'id_kecamatan' => '121'),
			array('nama' => 'Rantau Buta', 'id_kecamatan' => '121'),
			array('nama' => 'Rantau Layung', 'id_kecamatan' => '121'),
			array('nama' => 'Samuranggau', 'id_kecamatan' => '121'),
			array('nama' => 'Songka', 'id_kecamatan' => '121'),
			array('nama' => 'Sungai Terik', 'id_kecamatan' => '121'),
			
			array('nama' => 'Air Mati', 'id_kecamatan' => '122'),
			array('nama' => 'Keluang Lolo', 'id_kecamatan' => '122'),
			array('nama' => 'Keluang Paser Jaya', 'id_kecamatan' => '122'),
			array('nama' => 'Kendarom', 'id_kecamatan' => '122'),
			array('nama' => 'Kerta Bumi', 'id_kecamatan' => '122'),
			array('nama' => 'Klempang Sari', 'id_kecamatan' => '122'),
			array('nama' => 'Kuaro', 'id_kecamatan' => '122'),
			array('nama' => 'Modang', 'id_kecamatan' => '122'),
			array('nama' => 'Padang Jaya', 'id_kecamatan' => '122'),
			array('nama' => 'Pasir Mayang', 'id_kecamatan' => '122'),
			array('nama' => 'Pondang Baru', 'id_kecamatan' => '122'),
			array('nama' => 'Rangan', 'id_kecamatan' => '122'),
			array('nama' => 'Sandeley', 'id_kecamatan' => '122'),
			
			array('nama' => 'Adang Jaya', 'id_kecamatan' => '123'),
			array('nama' => 'Atang Pait', 'id_kecamatan' => '123'),
			array('nama' => 'Belimbing', 'id_kecamatan' => '123'),
			array('nama' => 'Brewe', 'id_kecamatan' => '123'),
			array('nama' => 'Bukit Saloka', 'id_kecamatan' => '123'),
			array('nama' => 'Jemparing', 'id_kecamatan' => '123'),
			array('nama' => 'Kayungo', 'id_kecamatan' => '123'),
			array('nama' => 'Kayungo Sari', 'id_kecamatan' => '123'),
			array('nama' => 'Kerta Bhakti', 'id_kecamatan' => '123'),
			array('nama' => 'Krayan Bahagia', 'id_kecamatan' => '123'),
			array('nama' => 'Krayan Jaya', 'id_kecamatan' => '123'),
			array('nama' => 'Krayan Makmur', 'id_kecamatan' => '123'),
			array('nama' => 'Krayan Sentosa', 'id_kecamatan' => '123'),
			array('nama' => 'Lombok', 'id_kecamatan' => '123'),
			array('nama' => 'Long Gelang', 'id_kecamatan' => '123'),
			array('nama' => 'Long Ikis', 'id_kecamatan' => '123'),
			array('nama' => 'Muara Adang', 'id_kecamatan' => '123'),
			array('nama' => 'Olung', 'id_kecamatan' => '123'),
			array('nama' => 'Pait', 'id_kecamatan' => '123'),
			array('nama' => 'Samuntai', 'id_kecamatan' => '123'),
			array('nama' => 'Sawit Jaya', 'id_kecamatan' => '123'),
			array('nama' => 'Sekurou Jaya', 'id_kecamatan' => '123'),
			array('nama' => 'Tajur Mulya', 'id_kecamatan' => '123'),
			array('nama' => 'Tajur', 'id_kecamatan' => '123'),
			array('nama' => 'Teluk Waru', 'id_kecamatan' => '123'),
			array('nama' => 'Tiwei', 'id_kecamatan' => '123'),

		);

		$temp4 = array(

			array('nama' => 'Bente Tualan', 'id_kecamatan' => '124'),
			array('nama' => 'Gunung Putar', 'id_kecamatan' => '124'),
			array('nama' => 'Kepala Telake', 'id_kecamatan' => '124'),
			array('nama' => 'Long Kali', 'id_kecamatan' => '124'),
			array('nama' => 'Makmur Jaya', 'id_kecamatan' => '124'),
			array('nama' => 'Maruat', 'id_kecamatan' => '124'),
			array('nama' => 'Mendik', 'id_kecamatan' => '124'),
			array('nama' => 'Mendik Bhakti', 'id_kecamatan' => '124'),
			array('nama' => 'Mendik Karya', 'id_kecamatan' => '124'),
			array('nama' => 'Mendik Makmur', 'id_kecamatan' => '124'),
			array('nama' => 'Muara Adang II', 'id_kecamatan' => '124'),
			array('nama' => 'Muara Lembakan', 'id_kecamatan' => '124'),
			array('nama' => 'Muara Pias', 'id_kecamatan' => '124'),
			array('nama' => 'Muara Telake', 'id_kecamatan' => '124'),
			array('nama' => 'Muara Toyu', 'id_kecamatan' => '124'),
			array('nama' => 'Munggu', 'id_kecamatan' => '124'),
			array('nama' => 'Perkuwen', 'id_kecamatan' => '124'),
			array('nama' => 'Petiku', 'id_kecamatan' => '124'),
			array('nama' => 'Pinang Jatus', 'id_kecamatan' => '124'),
			array('nama' => 'Putang', 'id_kecamatan' => '124'),
			array('nama' => 'Sembakung Makmur', 'id_kecamatan' => '124'),
			array('nama' => 'Sembakung Taka', 'id_kecamatan' => '124'),
			array('nama' => 'Sembakung', 'id_kecamatan' => '124'),
			
			array('nama' => 'Batu Butok', 'id_kecamatan' => '125'),
			array('nama' => 'Binangon', 'id_kecamatan' => '125'),
			array('nama' => 'Long Sayo', 'id_kecamatan' => '125'),
			array('nama' => 'Lusan', 'id_kecamatan' => '125'),
			array('nama' => 'Muara Koman', 'id_kecamatan' => '125'),
			array('nama' => 'Muara Kuaro', 'id_kecamatan' => '125'),
			array('nama' => 'Muara Langon', 'id_kecamatan' => '125'),
			array('nama' => 'Muara Payang', 'id_kecamatan' => '125'),
			array('nama' => 'Prayon', 'id_kecamatan' => '125'),
			array('nama' => 'Sekuan Makmur', 'id_kecamatan' => '125'),
			array('nama' => 'Selerong', 'id_kecamatan' => '125'),
			array('nama' => 'Swan Slutung', 'id_kecamatan' => '125'),
			array('nama' => 'Uko', 'id_kecamatan' => '125'),
			
			array('nama' => 'Biu', 'id_kecamatan' => '126'),
			array('nama' => 'Libur Dinding', 'id_kecamatan' => '126'),
			array('nama' => 'Luan', 'id_kecamatan' => '126'),
			array('nama' => 'Muara Andeh', 'id_kecamatan' => '126'),
			array('nama' => 'Muser', 'id_kecamatan' => '126'),
			array('nama' => 'Rantau Atas', 'id_kecamatan' => '126'),
			array('nama' => 'Rantau Bintungan', 'id_kecamatan' => '126'),
			array('nama' => 'Suweto', 'id_kecamatan' => '126'),
			array('nama' => 'Tanjung Pinang', 'id_kecamatan' => '126'),
			
			array('nama' => 'Bekoso', 'id_kecamatan' => '127'),
			array('nama' => 'Damit', 'id_kecamatan' => '127'),
			array('nama' => 'Lemburan', 'id_kecamatan' => '127'),
			array('nama' => 'Lemburan Baru', 'id_kecamatan' => '127'),
			array('nama' => 'Lempesu', 'id_kecamatan' => '127'),
			array('nama' => 'Olong Pinang', 'id_kecamatan' => '127'),
			array('nama' => 'Pasir Balengkong', 'id_kecamatan' => '127'),
			array('nama' => 'Sangkuriman', 'id_kecamatan' => '127'),
			array('nama' => 'Seniung Jaya', 'id_kecamatan' => '127'),
			array('nama' => 'Suatang', 'id_kecamatan' => '127'),
			array('nama' => 'Suatang Baru', 'id_kecamatan' => '127'),
			array('nama' => 'Suatang Keteban', 'id_kecamatan' => '127'),
			array('nama' => 'Suliliran', 'id_kecamatan' => '127'),
			array('nama' => 'Suliliran Baru', 'id_kecamatan' => '127'),
			array('nama' => 'Sunge Batu', 'id_kecamatan' => '127'),
			
			array('nama' => 'Janju', 'id_kecamatan' => '128'),
			array('nama' => 'Jone', 'id_kecamatan' => '128'),
			array('nama' => 'Muarapasir', 'id_kecamatan' => '128'),
			array('nama' => 'Padang Pengrapat', 'id_kecamatan' => '128'),
			array('nama' => 'Pepara', 'id_kecamatan' => '128'),
			array('nama' => 'Perepat', 'id_kecamatan' => '128'),
			array('nama' => 'Pulau Rantau', 'id_kecamatan' => '128'),
			array('nama' => 'Rantau Panjang', 'id_kecamatan' => '128'),
			array('nama' => 'Sempulang', 'id_kecamatan' => '128'),
			array('nama' => 'Senaken', 'id_kecamatan' => '128'),
			array('nama' => 'Sungai Tuak', 'id_kecamatan' => '128'),
			array('nama' => 'Sungai Langir', 'id_kecamatan' => '128'),
			array('nama' => 'Tanah Grogot', 'id_kecamatan' => '128'),
			array('nama' => 'Tanah Periuk', 'id_kecamatan' => '128'),
			array('nama' => 'Tapis', 'id_kecamatan' => '128'),
			array('nama' => 'Tepian Batang', 'id_kecamatan' => '128'),
			
			array('nama' => 'Keladen', 'id_kecamatan' => '129'),
			array('nama' => 'Labuangkallo', 'id_kecamatan' => '129'),
			array('nama' => 'Lori', 'id_kecamatan' => '129'),
			array('nama' => 'Random', 'id_kecamatan' => '129'),
			array('nama' => 'Selengot', 'id_kecamatan' => '129'),
			array('nama' => 'Senipah', 'id_kecamatan' => '129'),
			array('nama' => 'Tanjungaru', 'id_kecamatan' => '129'),

			# Penajam Paser Utara
			array('nama' => 'Babulu Darat', 'id_kecamatan' => '130'),
			array('nama' => 'Babulu Laut', 'id_kecamatan' => '130'),
			array('nama' => 'Gunung Intan', 'id_kecamatan' => '130'),
			array('nama' => 'Gunung Makmur', 'id_kecamatan' => '130'),
			array('nama' => 'Gunung Mulya', 'id_kecamatan' => '130'),
			array('nama' => 'Labangka', 'id_kecamatan' => '130'),
			array('nama' => 'Labangka Barat', 'id_kecamatan' => '130'),
			array('nama' => 'Rawa Mulya', 'id_kecamatan' => '130'),
			array('nama' => 'Rintik', 'id_kecamatan' => '130'),
			array('nama' => 'Sebakung Jaya', 'id_kecamatan' => '130'),
			array('nama' => 'Sri Raharja', 'id_kecamatan' => '130'),
			array('nama' => 'Sumber Sari', 'id_kecamatan' => '130'),
			
			array('nama' => 'Bukit Subur', 'id_kecamatan' => '131'),
			array('nama' => 'Buluminung', 'id_kecamatan' => '131'),
			array('nama' => 'Gersik', 'id_kecamatan' => '131'),
			array('nama' => 'Giri Mukti', 'id_kecamatan' => '131'),
			array('nama' => 'Giripurwa', 'id_kecamatan' => '131'),
			array('nama' => 'Gunung Seteleng', 'id_kecamatan' => '131'),
			array('nama' => 'Jenenbora', 'id_kecamatan' => '131'),
			array('nama' => 'Kampung Baru', 'id_kecamatan' => '131'),
			array('nama' => 'Lawe-Lawe', 'id_kecamatan' => '131'),
			array('nama' => 'Nenang', 'id_kecamatan' => '131'),
			array('nama' => 'Nipah-Nipah', 'id_kecamatan' => '131'),
			array('nama' => 'Pantai Lango', 'id_kecamatan' => '131'),
			array('nama' => 'Pejala', 'id_kecamatan' => '131'),
			array('nama' => 'Penajam', 'id_kecamatan' => '131'),
			array('nama' => 'Petung', 'id_kecamatan' => '131'),
			array('nama' => 'Riko', 'id_kecamatan' => '131'),
			array('nama' => 'Salo Loang', 'id_kecamatan' => '131'),
			array('nama' => 'Sepan', 'id_kecamatan' => '131'),
			array('nama' => 'Sesumpu', 'id_kecamatan' => '131'),
			array('nama' => 'Sidorejo', 'id_kecamatan' => '131'),
			array('nama' => 'Sotek', 'id_kecamatan' => '131'),
			array('nama' => 'Sungai Parit', 'id_kecamatan' => '131'),
			array('nama' => 'Tanjung Tengah', 'id_kecamatan' => '131'),

			array('nama' => 'Argo Mulyo', 'id_kecamatan' => '132'),
			array('nama' => 'Binuang', 'id_kecamatan' => '132'),
			array('nama' => 'Bukit Raya', 'id_kecamatan' => '132'),
			array('nama' => 'Bumi Harapan', 'id_kecamatan' => '132'),
			array('nama' => 'Karang Jinawi', 'id_kecamatan' => '132'),
			array('nama' => 'Meridan', 'id_kecamatan' => '132'),
			array('nama' => 'Mentawir', 'id_kecamatan' => '132'),
			array('nama' => 'Pemaluan', 'id_kecamatan' => '132'),
			array('nama' => 'Semoi Dua', 'id_kecamatan' => '132'),
			array('nama' => 'Sepaku', 'id_kecamatan' => '132'),
			array('nama' => 'Suka Raja', 'id_kecamatan' => '132'),
			array('nama' => 'Suko Mulyo', 'id_kecamatan' => '132'),
			array('nama' => 'Telemow', 'id_kecamatan' => '132'),
			array('nama' => 'Tengin Baru', 'id_kecamatan' => '132'),
			array('nama' => 'Wong Sari', 'id_kecamatan' => '132'),

			array('nama' => 'Api-Api', 'id_kecamatan' => '133'),
			array('nama' => 'Bangun Mulya', 'id_kecamatan' => '133'),
			array('nama' => 'Sesulu', 'id_kecamatan' => '133'),
			array('nama' => 'Waru', 'id_kecamatan' => '133'),

			# Samarinda
			array('nama' => 'Harapan Baru', 'id_kecamatan' => '134'),
			array('nama' => 'Rapak Dalam', 'id_kecamatan' => '134'),
			array('nama' => 'Sengkotek', 'id_kecamatan' => '134'),
			array('nama' => 'Loa Janan Ilir', 'id_kecamatan' => '134'),
			array('nama' => 'Tani Aman', 'id_kecamatan' => '134'),
			
			array('nama' => 'Bantuas', 'id_kecamatan' => '135'),
			array('nama' => 'Bukuan', 'id_kecamatan' => '135'),
			array('nama' => 'Handil Bakti', 'id_kecamatan' => '135'),
			array('nama' => 'Rawa Makmur', 'id_kecamatan' => '135'),
			array('nama' => 'Simpang Pasir', 'id_kecamatan' => '135'),
			
			array('nama' => 'Pelia', 'id_kecamatan' => '136'),
			array('nama' => 'Selili', 'id_kecamatan' => '136'),
			array('nama' => 'Sidodamai', 'id_kecamatan' => '136'),
			array('nama' => 'Sidomulyo', 'id_kecamatan' => '136'),
			array('nama' => 'Sungai Dama', 'id_kecamatan' => '136'),
			
			array('nama' => 'Bugis', 'id_kecamatan' => '137'),
			array('nama' => 'Karang Mumud', 'id_kecamatan' => '137'),
			array('nama' => 'Pasar Pagi', 'id_kecamatan' => '137'),
			array('nama' => 'Pelabuhan', 'id_kecamatan' => '137'),
			array('nama' => 'Sungai Pinang Dalam', 'id_kecamatan' => '137'),
			
			array('nama' => 'Rapak Dalam', 'id_kecamatan' => '138'),
			array('nama' => 'Mesjid', 'id_kecamatan' => '138'),
			array('nama' => 'Sungai Keledang', 'id_kecamatan' => '138'),
			
			array('nama' => 'Air Hitam', 'id_kecamatan' => '139'),
			array('nama' => 'Air Putih', 'id_kecamatan' => '139'),
			array('nama' => 'Bukit Pinang', 'id_kecamatan' => '139'),
			array('nama' => 'Dadi Mulya', 'id_kecamatan' => '139'),
			array('nama' => 'Gunung Kelua', 'id_kecamatan' => '139'),
			array('nama' => 'Jawa', 'id_kecamatan' => '139'),
			array('nama' => 'Sidodadi', 'id_kecamatan' => '139'),
			array('nama' => 'Teluk Lerong Ilir', 'id_kecamatan' => '139'),
			
			array('nama' => 'Lempake', 'id_kecamatan' => '140'),
			array('nama' => 'Sempaja Selatan', 'id_kecamatan' => '140'),
			array('nama' => 'Sempaja Utara', 'id_kecamatan' => '140'),
			array('nama' => 'Sungai Siring', 'id_kecamatan' => '140'),
			array('nama' => 'Tanah Merah', 'id_kecamatan' => '140'),
			
			array('nama' => 'Makroman', 'id_kecamatan' => '141'),
			array('nama' => 'Pulau Atas', 'id_kecamatan' => '141'),
			array('nama' => 'Sambutan', 'id_kecamatan' => '141'),
			array('nama' => 'Sindang Sari', 'id_kecamatan' => '141'),
			array('nama' => 'Sungai Kapih', 'id_kecamatan' => '141'),
			
			array('nama' => 'Karang Anyar', 'id_kecamatan' => '142'),
			array('nama' => 'Karang Asam Ilir', 'id_kecamatan' => '142'),
			array('nama' => 'Karang Asam Ulu', 'id_kecamatan' => '142'),
			array('nama' => 'Loa Bakung', 'id_kecamatan' => '142'),
			array('nama' => 'Loa Buah', 'id_kecamatan' => '142'),
			array('nama' => 'Loa Bahu', 'id_kecamatan' => '142'),
			array('nama' => 'Teluk Lerong Ulu', 'id_kecamatan' => '142'),
			
			array('nama' => 'Bandara', 'id_kecamatan' => '143'),
			array('nama' => 'Gunung Lingai', 'id_kecamatan' => '143'),
			array('nama' => 'Mugirejo', 'id_kecamatan' => '143'),
			array('nama' => 'Sungai Pinang Dalam', 'id_kecamatan' => '143'),
			array('nama' => 'Temindung Permai', 'id_kecamatan' => '143'),

			# Tana Tidung
			array('nama' => 'Bebakung', 'id_kecamatan' => '144'),
			array('nama' => 'Buong Baru', 'id_kecamatan' => '144'),
			array('nama' => 'Kujau', 'id_kecamatan' => '144'),
			array('nama' => 'Maning', 'id_kecamatan' => '144'),
			array('nama' => 'Mendupo', 'id_kecamatan' => '144'),
			array('nama' => 'Periuk', 'id_kecamatan' => '144'),
			
			array('nama' => 'Gunawan', 'id_kecamatan' => '145'),
			array('nama' => 'Limbu Sidulun', 'id_kecamatan' => '145'),
			array('nama' => 'Rian', 'id_kecamatan' => '145'),
			array('nama' => 'Sebawang', 'id_kecamatan' => '145'),
			array('nama' => 'Sebidai', 'id_kecamatan' => '145'),
			array('nama' => 'Sedulun', 'id_kecamatan' => '145'),
			array('nama' => 'Seputuk', 'id_kecamatan' => '145'),
			array('nama' => 'Tidung Pale', 'id_kecamatan' => '145'),
			array('nama' => 'Tidung Pale Timur', 'id_kecamatan' => '145'),
			
			array('nama' => 'Badan Bikis', 'id_kecamatan' => '146'),
			array('nama' => 'Bebatu', 'id_kecamatan' => '146'),
			array('nama' => 'Menjelutung', 'id_kecamatan' => '146'),
			array('nama' => 'Seludau', 'id_kecamatan' => '146'),
			array('nama' => 'Sengkong', 'id_kecamatan' => '146'),
			array('nama' => 'Sesayap Dalung', 'id_kecamatan' => '146'),
			array('nama' => 'Sesayap', 'id_kecamatan' => '146'),
			
			array('nama' => 'Sambungan', 'id_kecamatan' => '147'),
			array('nama' => 'Tanah Merah', 'id_kecamatan' => '147'),
			array('nama' => 'Tengku Dacing', 'id_kecamatan' => '147'),

			# Tarakan
			array('nama' => 'Karang Anyar', 'id_kecamatan' => '148'),
			array('nama' => 'Karang Anyar Pantai', 'id_kecamatan' => '148'),
			array('nama' => 'Karang Balik', 'id_kecamatan' => '148'),
			array('nama' => 'Karang Harapan', 'id_kecamatan' => '148'),
			array('nama' => 'Karang Rejo', 'id_kecamatan' => '148'),
			
			array('nama' => 'Kampung Siap Skip', 'id_kecamatan' => '149'),
			array('nama' => 'Pamusian', 'id_kecamatan' => '149'),
			array('nama' => 'Sebengkok', 'id_kecamatan' => '149'),
			array('nama' => 'Selumit', 'id_kecamatan' => '149'),
			array('nama' => 'Selumit Pantai', 'id_kecamatan' => '149'),
			
			array('nama' => 'Gunung Lingkas', 'id_kecamatan' => '150'),
			array('nama' => 'Kampung Empat', 'id_kecamatan' => '150'),
			array('nama' => 'Kampung Enam', 'id_kecamatan' => '150'),
			array('nama' => 'Lingkas Ujung', 'id_kecamatan' => '150'),
			array('nama' => 'Mamburungan', 'id_kecamatan' => '150'),
			array('nama' => 'Mamburungan Timur', 'id_kecamatan' => '150'),
			array('nama' => 'Pantai Amal', 'id_kecamatan' => '150'),
			
			array('nama' => 'Juata Kerikil', 'id_kecamatan' => '151'),
			array('nama' => 'Juata Laut', 'id_kecamatan' => '151'),
			array('nama' => 'Juata Permai', 'id_kecamatan' => '151'),
			
		);
		
		DB::table('kelurahan_desa')->insert($temp1);
		DB::table('kelurahan_desa')->insert($temp2);
		DB::table('kelurahan_desa')->insert($temp3);
		DB::table('kelurahan_desa')->insert($temp4);
	}

}